# Sbf1 Barcodes in 96 Well Plate

| well | Barcode | Name (top)      | Final top sequence                            | well | Name (bottom)   | Final bottom sequence                          |
|------|---------|-----------------|-----------------------------------------------|------|-----------------|------------------------------------------------|
| A1   | AAACGG  | SbfI-AAACGG-top | ACACTCTTTCCCTACACGACGCTCTTCCGATCTAAACGGTGC\*A | A1   | SbfI-AAACGG-bot | /5Phos/CCGTTTAGATCGGAAGAGCGTCGTGTAGGGAAAGAGTGT |
| A2   | AACGTT  | SbfI-AACGTT-top | ACACTCTTTCCCTACACGACGCTCTTCCGATCTAACGTTTGC\*A | A2   | SbfI-AACGTT-bot | /5Phos/AACGTTAGATCGGAAGAGCGTCGTGTAGGGAAAGAGTGT |
| A3   | AACTGA  | SbfI-AACTGA-top | ACACTCTTTCCCTACACGACGCTCTTCCGATCTAACTGATGC\*A | A3   | SbfI-AACTGA-bot | /5Phos/TCAGTTAGATCGGAAGAGCGTCGTGTAGGGAAAGAGTGT |
| A4   | AAGACG  | SbfI-AAGACG-top | ACACTCTTTCCCTACACGACGCTCTTCCGATCTAAGACGTGC\*A | A4   | SbfI-AAGACG-bot | /5Phos/CGTCTTAGATCGGAAGAGCGTCGTGTAGGGAAAGAGTGT |
| A5   | AAGCTA  | SbfI-AAGCTA-top | ACACTCTTTCCCTACACGACGCTCTTCCGATCTAAGCTATGC\*A | A5   | SbfI-AAGCTA-bot | /5Phos/TAGCTTAGATCGGAAGAGCGTCGTGTAGGGAAAGAGTGT |
| A6   | AATATC  | SbfI-AATATC-top | ACACTCTTTCCCTACACGACGCTCTTCCGATCTAATATCTGC\*A | A6   | SbfI-AATATC-bot | /5Phos/GATATTAGATCGGAAGAGCGTCGTGTAGGGAAAGAGTGT |
| A7   | AATGAG  | SbfI-AATGAG-top | ACACTCTTTCCCTACACGACGCTCTTCCGATCTAATGAGTGC\*A | A7   | SbfI-AATGAG-bot | /5Phos/CTCATTAGATCGGAAGAGCGTCGTGTAGGGAAAGAGTGT |
| A8   | ACAAGA  | SbfI-ACAAGA-top | ACACTCTTTCCCTACACGACGCTCTTCCGATCTACAAGATGC\*A | A8   | SbfI-ACAAGA-bot | /5Phos/TCTTGTAGATCGGAAGAGCGTCGTGTAGGGAAAGAGTGT |
| A9   | ACAGCG  | SbfI-ACAGCG-top | ACACTCTTTCCCTACACGACGCTCTTCCGATCTACAGCGTGC\*A | A9   | SbfI-ACAGCG-bot | /5Phos/CGCTGTAGATCGGAAGAGCGTCGTGTAGGGAAAGAGTGT |
| A10  | ACATAC  | SbfI-ACATAC-top | ACACTCTTTCCCTACACGACGCTCTTCCGATCTACATACTGC\*A | A10  | SbfI-ACATAC-bot | /5Phos/GTATGTAGATCGGAAGAGCGTCGTGTAGGGAAAGAGTGT |
| A11  | ACCATG  | SbfI-ACCATG-top | ACACTCTTTCCCTACACGACGCTCTTCCGATCTACCATGTGC\*A | A11  | SbfI-ACCATG-bot | /5Phos/CATGGTAGATCGGAAGAGCGTCGTGTAGGGAAAGAGTGT |
| A12  | ACCCCC  | SbfI-ACCCCC-top | ACACTCTTTCCCTACACGACGCTCTTCCGATCTACCCCCTGC\*A | A12  | SbfI-ACCCCC-bot | /5Phos/GGGGGTAGATCGGAAGAGCGTCGTGTAGGGAAAGAGTGT |
| B1   | ACTCTT  | SbfI-ACTCTT-top | ACACTCTTTCCCTACACGACGCTCTTCCGATCTACTCTTTGC\*A | B1   | SbfI-ACTCTT-bot | /5Phos/AAGAGTAGATCGGAAGAGCGTCGTGTAGGGAAAGAGTGT |
| B2   | ACTGGC  | SbfI-ACTGGC-top | ACACTCTTTCCCTACACGACGCTCTTCCGATCTACTGGCTGC\*A | B2   | SbfI-ACTGGC-bot | /5Phos/GCCAGTAGATCGGAAGAGCGTCGTGTAGGGAAAGAGTGT |
| B3   | AGCCAT  | SbfI-AGCCAT-top | ACACTCTTTCCCTACACGACGCTCTTCCGATCTAGCCATTGC\*A | B3   | SbfI-AGCCAT-bot | /5Phos/ATGGCTAGATCGGAAGAGCGTCGTGTAGGGAAAGAGTGT |
| B4   | AGCGCA  | SbfI-AGCGCA-top | ACACTCTTTCCCTACACGACGCTCTTCCGATCTAGCGCATGC\*A | B4   | SbfI-AGCGCA-bot | /5Phos/TGCGCTAGATCGGAAGAGCGTCGTGTAGGGAAAGAGTGT |
| B5   | AGGGTC  | SbfI-AGGGTC-top | ACACTCTTTCCCTACACGACGCTCTTCCGATCTAGGGTCTGC\*A | B5   | SbfI-AGGGTC-bot | /5Phos/GACCCTAGATCGGAAGAGCGTCGTGTAGGGAAAGAGTGT |
| B6   | AGGTGT  | SbfI-AGGTGT-top | ACACTCTTTCCCTACACGACGCTCTTCCGATCTAGGTGTTGC\*A | B6   | SbfI-AGGTGT-bot | /5Phos/ACACCTAGATCGGAAGAGCGTCGTGTAGGGAAAGAGTGT |
| B7   | AGTAGG  | SbfI-AGTAGG-top | ACACTCTTTCCCTACACGACGCTCTTCCGATCTAGTAGGTGC\*A | B7   | SbfI-AGTAGG-bot | /5Phos/CCTACTAGATCGGAAGAGCGTCGTGTAGGGAAAGAGTGT |
| B8   | AGTTAA  | SbfI-AGTTAA-top | ACACTCTTTCCCTACACGACGCTCTTCCGATCTAGTTAATGC\*A | B8   | SbfI-AGTTAA-bot | /5Phos/TTAACTAGATCGGAAGAGCGTCGTGTAGGGAAAGAGTGT |
| B9   | ATAGTA  | SbfI-ATAGTA-top | ACACTCTTTCCCTACACGACGCTCTTCCGATCTATAGTATGC\*A | B9   | SbfI-ATAGTA-bot | /5Phos/TACTATAGATCGGAAGAGCGTCGTGTAGGGAAAGAGTGT |
| B10  | ATCAAA  | SbfI-ATCAAA-top | ACACTCTTTCCCTACACGACGCTCTTCCGATCTATCAAATGC\*A | B10  | SbfI-ATCAAA-bot | /5Phos/TTTGATAGATCGGAAGAGCGTCGTGTAGGGAAAGAGTGT |
| B11  | ATGCAC  | SbfI-ATGCAC-top | ACACTCTTTCCCTACACGACGCTCTTCCGATCTATGCACTGC\*A | B11  | SbfI-ATGCAC-bot | /5Phos/GTGCATAGATCGGAAGAGCGTCGTGTAGGGAAAGAGTGT |
| B12  | ATGTTG  | SbfI-ATGTTG-top | ACACTCTTTCCCTACACGACGCTCTTCCGATCTATGTTGTGC\*A | B12  | SbfI-ATGTTG-bot | /5Phos/CAACATAGATCGGAAGAGCGTCGTGTAGGGAAAGAGTGT |
| C1   | ATTCCG  | SbfI-ATTCCG-top | ACACTCTTTCCCTACACGACGCTCTTCCGATCTATTCCGTGC\*A | C1   | SbfI-ATTCCG-bot | /5Phos/CGGAATAGATCGGAAGAGCGTCGTGTAGGGAAAGAGTGT |
| C2   | CAAAAA  | SbfI-CAAAAA-top | ACACTCTTTCCCTACACGACGCTCTTCCGATCTCAAAAATGC\*A | C2   | SbfI-CAAAAA-bot | /5Phos/TTTTTGAGATCGGAAGAGCGTCGTGTAGGGAAAGAGTGT |
| C3   | CAATCG  | SbfI-CAATCG-top | ACACTCTTTCCCTACACGACGCTCTTCCGATCTCAATCGTGC\*A | C3   | SbfI-CAATCG-bot | /5Phos/CGATTGAGATCGGAAGAGCGTCGTGTAGGGAAAGAGTGT |
| C4   | CACCTC  | SbfI-CACCTC-top | ACACTCTTTCCCTACACGACGCTCTTCCGATCTCACCTCTGC\*A | C4   | SbfI-CACCTC-bot | /5Phos/GAGGTGAGATCGGAAGAGCGTCGTGTAGGGAAAGAGTGT |
| C5   | CAGGCA  | SbfI-CAGGCA-top | ACACTCTTTCCCTACACGACGCTCTTCCGATCTCAGGCATGC\*A | C5   | SbfI-CAGGCA-bot | /5Phos/TGCCTGAGATCGGAAGAGCGTCGTGTAGGGAAAGAGTGT |
| C6   | CATACT  | SbfI-CATACT-top | ACACTCTTTCCCTACACGACGCTCTTCCGATCTCATACTTGC\*A | C6   | SbfI-CATACT-bot | /5Phos/AGTATGAGATCGGAAGAGCGTCGTGTAGGGAAAGAGTGT |
| C7   | CCATTT  | SbfI-CCATTT-top | ACACTCTTTCCCTACACGACGCTCTTCCGATCTCCATTTTGC\*A | C7   | SbfI-CCATTT-bot | /5Phos/AAATGGAGATCGGAAGAGCGTCGTGTAGGGAAAGAGTGT |
| C8   | CCCGGT  | SbfI-CCCGGT-top | ACACTCTTTCCCTACACGACGCTCTTCCGATCTCCCGGTTGC\*A | C8   | SbfI-CCCGGT-bot | /5Phos/ACCGGGAGATCGGAAGAGCGTCGTGTAGGGAAAGAGTGT |
| C9   | CCCTAA  | SbfI-CCCTAA-top | ACACTCTTTCCCTACACGACGCTCTTCCGATCTCCCTAATGC\*A | C9   | SbfI-CCCTAA-bot | /5Phos/TTAGGGAGATCGGAAGAGCGTCGTGTAGGGAAAGAGTGT |
| C10  | CCGAGG  | SbfI-CCGAGG-top | ACACTCTTTCCCTACACGACGCTCTTCCGATCTCCGAGGTGC\*A | C10  | SbfI-CCGAGG-bot | /5Phos/CCTCGGAGATCGGAAGAGCGTCGTGTAGGGAAAGAGTGT |
| C11  | CCGCAT  | SbfI-CCGCAT-top | ACACTCTTTCCCTACACGACGCTCTTCCGATCTCCGCATTGC\*A | C11  | SbfI-CCGCAT-bot | /5Phos/ATGCGGAGATCGGAAGAGCGTCGTGTAGGGAAAGAGTGT |
| C12  | CCTAAC  | SbfI-CCTAAC-top | ACACTCTTTCCCTACACGACGCTCTTCCGATCTCCTAACTGC\*A | C12  | SbfI-CCTAAC-bot | /5Phos/GTTAGGAGATCGGAAGAGCGTCGTGTAGGGAAAGAGTGT |
| D1   | CGAGGC  | SbfI-CGAGGC-top | ACACTCTTTCCCTACACGACGCTCTTCCGATCTCGAGGCTGC\*A | D1   | SbfI-CGAGGC-bot | /5Phos/GCCTCGAGATCGGAAGAGCGTCGTGTAGGGAAAGAGTGT |
| D2   | CGCAGA  | SbfI-CGCAGA-top | ACACTCTTTCCCTACACGACGCTCTTCCGATCTCGCAGATGC\*A | D2   | SbfI-CGCAGA-bot | /5Phos/TCTGCGAGATCGGAAGAGCGTCGTGTAGGGAAAGAGTGT |
| D3   | CGCGTG  | SbfI-CGCGTG-top | ACACTCTTTCCCTACACGACGCTCTTCCGATCTCGCGTGTGC\*A | D3   | SbfI-CGCGTG-bot | /5Phos/CACGCGAGATCGGAAGAGCGTCGTGTAGGGAAAGAGTGT |
| D4   | CGGTCC  | SbfI-CGGTCC-top | ACACTCTTTCCCTACACGACGCTCTTCCGATCTCGGTCCTGC\*A | D4   | SbfI-CGGTCC-bot | /5Phos/GGACCGAGATCGGAAGAGCGTCGTGTAGGGAAAGAGTGT |
| D5   | CGTCTA  | SbfI-CGTCTA-top | ACACTCTTTCCCTACACGACGCTCTTCCGATCTCGTCTATGC\*A | D5   | SbfI-CGTCTA-bot | /5Phos/TAGACGAGATCGGAAGAGCGTCGTGTAGGGAAAGAGTGT |
| D6   | CGTGAT  | SbfI-CGTGAT-top | ACACTCTTTCCCTACACGACGCTCTTCCGATCTCGTGATTGC\*A | D6   | SbfI-CGTGAT-bot | /5Phos/ATCACGAGATCGGAAGAGCGTCGTGTAGGGAAAGAGTGT |
| D7   | CTACAG  | SbfI-CTACAG-top | ACACTCTTTCCCTACACGACGCTCTTCCGATCTCTACAGTGC\*A | D7   | SbfI-CTACAG-bot | /5Phos/CTGTAGAGATCGGAAGAGCGTCGTGTAGGGAAAGAGTGT |
| D8   | CTCGCC  | SbfI-CTCGCC-top | ACACTCTTTCCCTACACGACGCTCTTCCGATCTCTCGCCTGC\*A | D8   | SbfI-CTCGCC-bot | /5Phos/GGCGAGAGATCGGAAGAGCGTCGTGTAGGGAAAGAGTGT |
| D9   | CTGCGA  | SbfI-CTGCGA-top | ACACTCTTTCCCTACACGACGCTCTTCCGATCTCTGCGATGC\*A | D9   | SbfI-CTGCGA-bot | /5Phos/TCGCAGAGATCGGAAGAGCGTCGTGTAGGGAAAGAGTGT |
| D10  | CTGGTT  | SbfI-CTGGTT-top | ACACTCTTTCCCTACACGACGCTCTTCCGATCTCTGGTTTGC\*A | D10  | SbfI-CTGGTT-bot | /5Phos/AACCAGAGATCGGAAGAGCGTCGTGTAGGGAAAGAGTGT |
| D11  | CTTATG  | SbfI-CTTATG-top | ACACTCTTTCCCTACACGACGCTCTTCCGATCTCTTATGTGC\*A | D11  | SbfI-CTTATG-bot | /5Phos/CATAAGAGATCGGAAGAGCGTCGTGTAGGGAAAGAGTGT |
| D12  | CTTTGC  | SbfI-CTTTGC-top | ACACTCTTTCCCTACACGACGCTCTTCCGATCTCTTTGCTGC\*A | D12  | SbfI-CTTTGC-bot | /5Phos/GCAAAGAGATCGGAAGAGCGTCGTGTAGGGAAAGAGTGT |
| E1   | GAAATG  | SbfI-GAAATG-top | ACACTCTTTCCCTACACGACGCTCTTCCGATCTGAAATGTGC\*A | E1   | SbfI-GAAATG-bot | /5Phos/CATTTCAGATCGGAAGAGCGTCGTGTAGGGAAAGAGTGT |
| E2   | GAACCA  | SbfI-GAACCA-top | ACACTCTTTCCCTACACGACGCTCTTCCGATCTGAACCATGC\*A | E2   | SbfI-GAACCA-bot | /5Phos/TGGTTCAGATCGGAAGAGCGTCGTGTAGGGAAAGAGTGT |
| E3   | GACGAC  | SbfI-GACGAC-top | ACACTCTTTCCCTACACGACGCTCTTCCGATCTGACGACTGC\*A | E3   | SbfI-GACGAC-bot | /5Phos/GTCGTCAGATCGGAAGAGCGTCGTGTAGGGAAAGAGTGT |
| E4   | GACTCT  | SbfI-GACTCT-top | ACACTCTTTCCCTACACGACGCTCTTCCGATCTGACTCTTGC\*A | E4   | SbfI-GACTCT-bot | /5Phos/AGAGTCAGATCGGAAGAGCGTCGTGTAGGGAAAGAGTGT |
| E5   | GAGAGA  | SbfI-GAGAGA-top | ACACTCTTTCCCTACACGACGCTCTTCCGATCTGAGAGATGC\*A | E5   | SbfI-GAGAGA-bot | /5Phos/TCTCTCAGATCGGAAGAGCGTCGTGTAGGGAAAGAGTGT |
| E6   | GATCGT  | SbfI-GATCGT-top | ACACTCTTTCCCTACACGACGCTCTTCCGATCTGATCGTTGC\*A | E6   | SbfI-GATCGT-bot | /5Phos/ACGATCAGATCGGAAGAGCGTCGTGTAGGGAAAGAGTGT |
| E7   | GCAGAT  | SbfI-GCAGAT-top | ACACTCTTTCCCTACACGACGCTCTTCCGATCTGCAGATTGC\*A | E7   | SbfI-GCAGAT-bot | /5Phos/ATCTGCAGATCGGAAGAGCGTCGTGTAGGGAAAGAGTGT |
| E8   | GCATGG  | SbfI-GCATGG-top | ACACTCTTTCCCTACACGACGCTCTTCCGATCTGCATGGTGC\*A | E8   | SbfI-GCATGG-bot | /5Phos/CCATGCAGATCGGAAGAGCGTCGTGTAGGGAAAGAGTGT |
| E9   | GCCGTA  | SbfI-GCCGTA-top | ACACTCTTTCCCTACACGACGCTCTTCCGATCTGCCGTATGC\*A | E9   | SbfI-GCCGTA-bot | /5Phos/TACGGCAGATCGGAAGAGCGTCGTGTAGGGAAAGAGTGT |
| E10  | GCGACC  | SbfI-GCGACC-top | ACACTCTTTCCCTACACGACGCTCTTCCGATCTGCGACCTGC\*A | E10  | SbfI-GCGACC-bot | /5Phos/GGTCGCAGATCGGAAGAGCGTCGTGTAGGGAAAGAGTGT |
| E11  | GCGCTG  | SbfI-GCGCTG-top | ACACTCTTTCCCTACACGACGCTCTTCCGATCTGCGCTGTGC\*A | E11  | SbfI-GCGCTG-bot | /5Phos/CAGCGCAGATCGGAAGAGCGTCGTGTAGGGAAAGAGTGT |
| E12  | GCTCAA  | SbfI-GCTCAA-top | ACACTCTTTCCCTACACGACGCTCTTCCGATCTGCTCAATGC\*A | E12  | SbfI-GCTCAA-bot | /5Phos/TTGAGCAGATCGGAAGAGCGTCGTGTAGGGAAAGAGTGT |
| F1   | GGACTT  | SbfI-GGACTT-top | ACACTCTTTCCCTACACGACGCTCTTCCGATCTGGACTTTGC\*A | F1   | SbfI-GGACTT-bot | /5Phos/AAGTCCAGATCGGAAGAGCGTCGTGTAGGGAAAGAGTGT |
| F2   | GGCAAG  | SbfI-GGCAAG-top | ACACTCTTTCCCTACACGACGCTCTTCCGATCTGGCAAGTGC\*A | F2   | SbfI-GGCAAG-bot | /5Phos/CTTGCCAGATCGGAAGAGCGTCGTGTAGGGAAAGAGTGT |
| F3   | GGGCGC  | SbfI-GGGCGC-top | ACACTCTTTCCCTACACGACGCTCTTCCGATCTGGGCGCTGC\*A | F3   | SbfI-GGGCGC-bot | /5Phos/GCGCCCAGATCGGAAGAGCGTCGTGTAGGGAAAGAGTGT |
| F4   | GGGGCG  | SbfI-GGGGCG-top | ACACTCTTTCCCTACACGACGCTCTTCCGATCTGGGGCGTGC\*A | F4   | SbfI-GGGGCG-bot | /5Phos/CGCCCCAGATCGGAAGAGCGTCGTGTAGGGAAAGAGTGT |
| F5   | GGTACA  | SbfI-GGTACA-top | ACACTCTTTCCCTACACGACGCTCTTCCGATCTGGTACATGC\*A | F5   | SbfI-GGTACA-bot | /5Phos/TGTACCAGATCGGAAGAGCGTCGTGTAGGGAAAGAGTGT |
| F6   | GGTTTG  | SbfI-GGTTTG-top | ACACTCTTTCCCTACACGACGCTCTTCCGATCTGGTTTGTGC\*A | F6   | SbfI-GGTTTG-bot | /5Phos/CAAACCAGATCGGAAGAGCGTCGTGTAGGGAAAGAGTGT |
| F7   | GTAAGT  | SbfI-GTAAGT-top | ACACTCTTTCCCTACACGACGCTCTTCCGATCTGTAAGTTGC\*A | F7   | SbfI-GTAAGT-bot | /5Phos/ACTTACAGATCGGAAGAGCGTCGTGTAGGGAAAGAGTGT |
| F8   | GTATCC  | SbfI-GTATCC-top | ACACTCTTTCCCTACACGACGCTCTTCCGATCTGTATCCTGC\*A | F8   | SbfI-GTATCC-bot | /5Phos/GGATACAGATCGGAAGAGCGTCGTGTAGGGAAAGAGTGT |
| F9   | GTCATC  | SbfI-GTCATC-top | ACACTCTTTCCCTACACGACGCTCTTCCGATCTGTCATCTGC\*A | F9   | SbfI-GTCATC-bot | /5Phos/GATGACAGATCGGAAGAGCGTCGTGTAGGGAAAGAGTGT |
| F10  | GTGCCT  | SbfI-GTGCCT-top | ACACTCTTTCCCTACACGACGCTCTTCCGATCTGTGCCTTGC\*A | F10  | SbfI-GTGCCT-bot | /5Phos/AGGCACAGATCGGAAGAGCGTCGTGTAGGGAAAGAGTGT |
| F11  | GTGTAA  | SbfI-GTGTAA-top | ACACTCTTTCCCTACACGACGCTCTTCCGATCTGTGTAATGC\*A | F11  | SbfI-GTGTAA-bot | /5Phos/TTACACAGATCGGAAGAGCGTCGTGTAGGGAAAGAGTGT |
| F12  | GTTGGA  | SbfI-GTTGGA-top | ACACTCTTTCCCTACACGACGCTCTTCCGATCTGTTGGATGC\*A | F12  | SbfI-GTTGGA-bot | /5Phos/TCCAACAGATCGGAAGAGCGTCGTGTAGGGAAAGAGTGT |
| G1   | TAAGCT  | SbfI-TAAGCT-top | ACACTCTTTCCCTACACGACGCTCTTCCGATCTTAAGCTTGC\*A | G1   | SbfI-TAAGCT-bot | /5Phos/AGCTTAAGATCGGAAGAGCGTCGTGTAGGGAAAGAGTGT |
| G2   | TAATTC  | SbfI-TAATTC-top | ACACTCTTTCCCTACACGACGCTCTTCCGATCTTAATTCTGC\*A | G2   | SbfI-TAATTC-bot | /5Phos/GAATTAAGATCGGAAGAGCGTCGTGTAGGGAAAGAGTGT |
| G3   | TACACA  | SbfI-TACACA-top | ACACTCTTTCCCTACACGACGCTCTTCCGATCTTACACATGC\*A | G3   | SbfI-TACACA-bot | /5Phos/TGTGTAAGATCGGAAGAGCGTCGTGTAGGGAAAGAGTGT |
| G4   | TACGGG  | SbfI-TACGGG-top | ACACTCTTTCCCTACACGACGCTCTTCCGATCTTACGGGTGC\*A | G4   | SbfI-TACGGG-bot | /5Phos/CCCGTAAGATCGGAAGAGCGTCGTGTAGGGAAAGAGTGT |
| G5   | TAGTAT  | SbfI-TAGTAT-top | ACACTCTTTCCCTACACGACGCTCTTCCGATCTTAGTATTGC\*A | G5   | SbfI-TAGTAT-bot | /5Phos/ATACTAAGATCGGAAGAGCGTCGTGTAGGGAAAGAGTGT |
| G6   | TATCAC  | SbfI-TATCAC-top | ACACTCTTTCCCTACACGACGCTCTTCCGATCTTATCACTGC\*A | G6   | SbfI-TATCAC-bot | /5Phos/GTGATAAGATCGGAAGAGCGTCGTGTAGGGAAAGAGTGT |
| G7   | TCAAAG  | SbfI-TCAAAG-top | ACACTCTTTCCCTACACGACGCTCTTCCGATCTTCAAAGTGC\*A | G7   | SbfI-TCAAAG-bot | /5Phos/CTTTGAAGATCGGAAGAGCGTCGTGTAGGGAAAGAGTGT |
| G8   | TCCTGC  | SbfI-TCCTGC-top | ACACTCTTTCCCTACACGACGCTCTTCCGATCTTCCTGCTGC\*A | G8   | SbfI-TCCTGC-bot | /5Phos/GCAGGAAGATCGGAAGAGCGTCGTGTAGGGAAAGAGTGT |
| G9   | TCGATT  | SbfI-TCGATT-top | ACACTCTTTCCCTACACGACGCTCTTCCGATCTTCGATTTGC\*A | G9   | SbfI-TCGATT-bot | /5Phos/AATCGAAGATCGGAAGAGCGTCGTGTAGGGAAAGAGTGT |
| G10  | TCGCCA  | SbfI-TCGCCA-top | ACACTCTTTCCCTACACGACGCTCTTCCGATCTTCGCCATGC\*A | G10  | SbfI-TCGCCA-bot | /5Phos/TGGCGAAGATCGGAAGAGCGTCGTGTAGGGAAAGAGTGT |
| G11  | TCGGAC  | SbfI-TCGGAC-top | ACACTCTTTCCCTACACGACGCTCTTCCGATCTTCGGACTGC\*A | G11  | SbfI-TCGGAC-bot | /5Phos/GTCCGAAGATCGGAAGAGCGTCGTGTAGGGAAAGAGTGT |
| G12  | TCTCGG  | SbfI-TCTCGG-top | ACACTCTTTCCCTACACGACGCTCTTCCGATCTTCTCGGTGC\*A | G12  | SbfI-TCTCGG-bot | /5Phos/CCGAGAAGATCGGAAGAGCGTCGTGTAGGGAAAGAGTGT |
| H1   | TCTTCT  | SbfI-TCTTCT-top | ACACTCTTTCCCTACACGACGCTCTTCCGATCTTCTTCTTGC\*A | H1   | SbfI-TCTTCT-bot | /5Phos/AGAAGAAGATCGGAAGAGCGTCGTGTAGGGAAAGAGTGT |
| H2   | TGAACC  | SbfI-TGAACC-top | ACACTCTTTCCCTACACGACGCTCTTCCGATCTTGAACCTGC\*A | H2   | SbfI-TGAACC-bot | /5Phos/GGTTCAAGATCGGAAGAGCGTCGTGTAGGGAAAGAGTGT |
| H3   | TGACAA  | SbfI-TGACAA-top | ACACTCTTTCCCTACACGACGCTCTTCCGATCTTGACAATGC\*A | H3   | SbfI-TGACAA-bot | /5Phos/TTGTCAAGATCGGAAGAGCGTCGTGTAGGGAAAGAGTGT |
| H4   | TGCCCG  | SbfI-TGCCCG-top | ACACTCTTTCCCTACACGACGCTCTTCCGATCTTGCCCGTGC\*A | H4   | SbfI-TGCCCG-bot | /5Phos/CGGGCAAGATCGGAAGAGCGTCGTGTAGGGAAAGAGTGT |
| H5   | TGCTTA  | SbfI-TGCTTA-top | ACACTCTTTCCCTACACGACGCTCTTCCGATCTTGCTTATGC\*A | H5   | SbfI-TGCTTA-bot | /5Phos/TAAGCAAGATCGGAAGAGCGTCGTGTAGGGAAAGAGTGT |
| H6   | TGGGGA  | SbfI-TGGGGA-top | ACACTCTTTCCCTACACGACGCTCTTCCGATCTTGGGGATGC\*A | H6   | SbfI-TGGGGA-bot | /5Phos/TCCCCAAGATCGGAAGAGCGTCGTGTAGGGAAAGAGTGT |
| H7   | TTATGA  | SbfI-TTATGA-top | ACACTCTTTCCCTACACGACGCTCTTCCGATCTTTATGATGC\*A | H7   | SbfI-TTATGA-bot | /5Phos/TCATAAAGATCGGAAGAGCGTCGTGTAGGGAAAGAGTGT |
| H8   | TTCCGT  | SbfI-TTCCGT-top | ACACTCTTTCCCTACACGACGCTCTTCCGATCTTTCCGTTGC\*A | H8   | SbfI-TTCCGT-bot | /5Phos/ACGGAAAGATCGGAAGAGCGTCGTGTAGGGAAAGAGTGT |
| H9   | TTCTAG  | SbfI-TTCTAG-top | ACACTCTTTCCCTACACGACGCTCTTCCGATCTTTCTAGTGC\*A | H9   | SbfI-TTCTAG-bot | /5Phos/CTAGAAAGATCGGAAGAGCGTCGTGTAGGGAAAGAGTGT |
| H10  | TTGAGC  | SbfI-TTGAGC-top | ACACTCTTTCCCTACACGACGCTCTTCCGATCTTTGAGCTGC\*A | H10  | SbfI-TTGAGC-bot | /5Phos/GCTCAAAGATCGGAAGAGCGTCGTGTAGGGAAAGAGTGT |
| H11  | TTTAAT  | SbfI-TTTAAT-top | ACACTCTTTCCCTACACGACGCTCTTCCGATCTTTTAATTGC\*A | H11  | SbfI-TTTAAT-bot | /5Phos/ATTAAAAGATCGGAAGAGCGTCGTGTAGGGAAAGAGTGT |
| H12  | TTTGTC  | SbfI-TTTGTC-top | ACACTCTTTCCCTACACGACGCTCTTCCGATCTTTTGTCTGC\*A | H12  | SbfI-TTTGTC-bot | /5Phos/GACAAAAGATCGGAAGAGCGTCGTGTAGGGAAAGAGTGT |
