project:
  type: book
  output-dir: docs

book:
  title: "Cresko Laboratory Procedures and Protocols"
  reader-mode: true
  downloads: [pdf, epub]
  page-footer:
    left: |
      The complete compendium of SOPs for the Cresko Laboratory
    right: |
      This book was built with <a href="https://quarto.org/">Quarto</a>.
  
  cover-image: images/CreskoLabLogo.png
  author: "Cresko Laboratory"
  date: now
  date-format: full
  
  chapters:
    - index.qmd
    
    - part: Part1_General.qmd
      chapters:
        - 01_General/General_Contact.qmd
        
    - part: Part2_Molecular.qmd
      chapters:
        - 02_Molecular/Molecular_cDNA.qmd
        - 02_Molecular/Molecular_2xTurbo.qmd
        - 02_Molecular/Molecular_Para.qmd
        - 02_Molecular/Molecular_Alizarin.qmd
        
    - part: Part3_Microbiology.qmd
      chapters:
        - 03_Microbiology/Placeholder_Microbiology.qmd
        
    - part: Part4_Vertebrate_Husbandry.qmd
      chapters:
        - 04_Vertebrate_Husbandry/Husbandry_20gallon.qmd
        - 04_Vertebrate_Husbandry/Husbandry_Artemia_Decapsulation.qmd
        - 04_Vertebrate_Husbandry/Husbandry_Embryo_and_Larval_Euthanasia_Syngnathid.qmd
        
    - part: Part5_Vertebrate_Experiment.qmd
      chapters:
        - 05_Vertebrate_Experiment/VertExperiment_Live_Alizarin_Staining_Syngnathid.qmd
        - 05_Vertebrate_Experiment/VertExperiment_Live_Calcein_Staining_Syngnathid.qmd
        - 05_Vertebrate_Experiment/VertExperiment_Live_Daspei_Staining_Syngnathid.qmd
        - 05_Vertebrate_Experiment/VertExperiment_Live_Fin_Clipping_Syngnathid.qmd
        - 05_Vertebrate_Experiment/VertExperiment_Field_Collection_Syngnathid.qmd
        - 05_Vertebrate_Experiment/VertExperiment_Field_Collection_Stickleback.qmd

    - part: Part6_Invertebrate_Husbandry.qmd
      chapters:
        - 06_Invertebrate/Placeholder_Daphnia.qmd
   
    - part: Part7_Bioinformatic.qmd
      chapters:
        - 07_Bioinformatic/base-R.qmd
  
    - part: Part8_References.qmd
      chapters:      
        - references.qmd
        - notes.qmd 

  appendices:
    - 08_Appendices/appendix_1.qmd
    - 08_Appendices/appendix_2.qmd
  
bibliography: references.bib

format:
  html:
    theme: cosmo
    number-depth: 1
  pdf:
    documentclass: scrreprt
    number-depth: 1
    include-in-header: 
      text: |
        \usepackage{makeidx}
        \makeindex
    include-after-body: 
      text: |
        \printindex
  epub:
    cover-image: images/CreskoLabLogo.png
    number-depth: 2
    
editor: visual

