project:
  type: book
  output-dir: docs

book:
  title: "Cresko Laboratory Procedures and Protocols"
  reader-mode: true
  downloads: [pdf, epub]
  page-footer:
    left: |
      The complete compendium of SOPs for the Cresko Laboratory
    right: |
      This book was built with <a href="https://quarto.org/">Quarto</a>.
  
  cover-image: images/CreskoLabLogo.png
  author: "William A. Cresko"
  date: now
  date-format: full
  
  chapters:
    - index.qmd
    
    - part: Part1_General.qmd
      chapters:
        - General_Contact.qmd
        
    - part: Part2_Molecular.qmd
      chapters:
        - Molecular_cDNA.qmd
        - Molecular_2xTurbo.qmd
        - Molecular_8%Para.qmd
        
    - part: Part3_Vertebrate_Husbandry.qmd
      chapters:
        - Husbandry_20gallon.qmd
        
    - part: Part4_Daphnia_Husbandry.qmd
      chapters:
        - Placeholder_Daphnia.qmd
   
    - part: Part5_Bioinformatic.qmd
      chapters:
        - base-R.qmd

    - summary.qmd
    - references.qmd  
    
  appendices:
    - appendix_1.qmd
    - appendix_2.qmd
  
bibliography: references.bib

format:
  html:
    theme: cosmo
    number-depth: 2
  pdf:
    documentclass: scrreprt
    number-depth: 2
    include-in-header: 
      text: |
        \usepackage{makeidx}
        \makeindex
    include-after-body: 
      text: |
        \printindex
  epub:
    cover-image: images/CreskoLabLogo.png
    number-depth: 2
    
editor: visual

