project:
  type: book
  output-dir: docs

book:
  title: "Cresko Laboratory Procedures and Protocols"
  reader-mode: true
  page-footer:
    left: |
      The complete compendium of SOPs for the Cresko Laboratory
    right: |
      This book was built with <a href="https://quarto.org/">Quarto</a>.
  
  cover-image: cover.png
  author: "William A. Cresko"
  date: "11/30/2023"
  chapters:
    - index.qmd
    
    - part: part_one.qmd
      chapters:
        - Husbandry_20gallon.qmd
        - Humbug.qmd
        - base-R.qmd
        
    - part: part_two.qmd
      chapters:
        - summary.qmd
        - references.qmd
        
  appendices:
    - appendix_1.qmd
    - appendix_2.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt

editor: visual

