project:
  type: book
  output-dir: docs

book:
  title: "Cresko Laboratory Procedures and Protocols"
  reader-mode: true
  downloads: [pdf, epub]
  page-footer:
    left: |
      The complete compendium of SOPs for the Cresko Laboratory
    right: |
      This book was built with <a href="https://quarto.org/">Quarto</a>.
  
  cover-image: images/CreskoLabLogo.png
  author: "Cresko Laboratory"
  date: now
  date-format: full
  
  chapters:
    - index.qmd
    
    - part: Part1_General.qmd
      chapters:
        - 01_General/General_Contact.qmd
        
    - part: Part2_Molecular.qmd
      chapters:
        - 02_Molecular/Molecular_cDNA.qmd
        - 02_Molecular/Molecular_2xTurbo.qmd
        - 02_Molecular/Molecular_Para.qmd
        
    - part: Part3_Microbiology.qmd
      chapters:
        - 03_Microbiology/Placeholder_Microbiology.qmd
        
    - part: Part4_Vertebrate_Husbandry.qmd
      chapters:
        - 04_Vertebrate/Husbandry_20gallon.qmd
        
    - part: Part5_Invertebrate_Husbandry.qmd
      chapters:
        - 05_Invertebrate/Placeholder_Daphnia.qmd
   
    - part: Part6_Bioinformatic.qmd
      chapters:
        - 06_Bioinformatic/base-R.qmd

    - summary.qmd
    - references.qmd  
    
  appendices:
    - 07_Appendices/appendix_1.qmd
    - 07_Appendices/appendix_2.qmd
  
bibliography: references.bib

format:
  html:
    theme: cosmo
    number-depth: 1
  pdf:
    documentclass: scrreprt
    number-depth: 1
    include-in-header: 
      text: |
        \usepackage{makeidx}
        \makeindex
    include-after-body: 
      text: |
        \printindex
  epub:
    cover-image: images/CreskoLabLogo.png
    number-depth: 2
    
editor: visual

