project:
  type: book
  output-dir: docs

book:
  title: "Cresko Laboratory Procedures and Protocols"
  reader-mode: true
  page-footer:
    left: |
      The complete compendium of SOPs for the Cresko Laboratory
    right: |
      This book was built with <a href="https://quarto.org/">Quarto</a>.
  
  cover-image: images/CreskoLabLogo.png
  author: "William A. Cresko"
  date: "11/30/2023"
  chapters:
    - index.qmd
    - intro.qmd
    
    - part: Part1_General.qmd
      chapters:
        - Husbandry_20gallon.qmd
        
    - part: Part2_Molecular.qmd
      chapters:
        - Placeholder_Molecular.qmd
        
    - part: Part3_Vertebrate_Husbandry.qmd
      chapters:
        - Husbandry_20gallon.qmd
        
    - part: Part4_Daphnia_Husbandry.qmd
      chapters:
        - Placeholder_Daphnia.qmd
   
    - part: Part5_Bioinformatic.qmd
      chapters:
        - base-R.qmd

    - summary.qmd
    - references.qmd  
    
  appendices:
    - appendix_1.qmd
    - appendix_2.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt

editor: visual

