project:
  type: book
  output-dir: docs

book:
  title: "Cresko Laboratory Procedures and Protocols"
  reader-mode: true
  downloads: [pdf, epub]
  page-footer:
    left: |
      The complete compendium of SOPs for the Cresko Laboratory
    right: |
      This book was built with <a href="https://quarto.org/">Quarto</a>.
  
  cover-image: images/CreskoLabLogo.png
  author: "Cresko Laboratory"
  date: now
  date-format: full
  
  chapters:
    - index.qmd
    
    - part: Part1_General.qmd
      chapters:
        - 01_General/General_Contact.qmd
        
    - part: Part2_Molecular.qmd
      chapters:
        - 02_Molecular/Molecular_Phusion_PCR.qmd
        - 02_Molecular/Molecular_cDNA.qmd
        - 02_Molecular/Molecular_2xTurbo.qmd
        - 02_Molecular/Molecular_Para.qmd
        - 02_Molecular/Molecular_Alizarin.qmd
        - 02_Molecular/Molecular_Pouring_and_Running_a_Gel.qmd
        
    - part: Part3_Microbiology.qmd
      chapters:
        - 03_Microbiology/Placeholder_Microbiology.qmd
        
    - part: Part4_Vertebrate_Husbandry.qmd
      chapters:
        - 04_Vertebrate_Husbandry/Husbandry_General_Autoclaving.qmd
        - 04_Vertebrate_Husbandry/Husbandry_General_20_gallon_tank_cleaning.qmd
        - 04_Vertebrate_Husbandry/Husbandry_General_Brine_Shrimp_decapsulation.qmd
        - 04_Vertebrate_Husbandry/Husbandry_General_BrineShrimp_Enrichment.qmd
        - 04_Vertebrate_Husbandry/Husbandry_General_Cleaning_Plastic_and_Glassware_with_Bleach.qmd
        - 04_Vertebrate_Husbandry/Husbandry_General_Fish_Food_Storage_Sources.qmd
        - 04_Vertebrate_Husbandry/Husbandry_General_Fry_tank_cleaning.qmd
        - 04_Vertebrate_Husbandry/Husbandry_General_Health_Check.qmd
        - 04_Vertebrate_Husbandry/Husbandry_General_Mysid_live_food_culture.qmd
        - 04_Vertebrate_Husbandry/Husbandry_General_Stickleback_DB_use.qmd
        - 04_Vertebrate_Husbandry/Husbandry_General_UV_Bulb.qmd
        - 04_Vertebrate_Husbandry/Husbandry_General_Weekday_Feeding_Health_Checks.qmd
        - 04_Vertebrate_Husbandry/Husbandry_General_Stickleback_Adult_Euthanasia.qmd
        - 04_Vertebrate_Husbandry/Husbandry_General_Syngnathid_Embryo_and_Larval_Euthanasia.qmd
        - 04_Vertebrate_Husbandry/Husbandry_General_Dishwasher_Use.qmd
        - 04_Vertebrate_Husbandry/Husbandry_General_Hatching_Feeding_BrineShrimp.qmd
        - 04_Vertebrate_Husbandry/Husbandry_General_Incubator_Use.qmd
        - 04_Vertebrate_Husbandry/Husbandry_General_Program_Light.qmd
        - 04_Vertebrate_Husbandry/Husbandry_General_Room_Clean.qmd
        - 04_Vertebrate_Husbandry/Husbandry_General_Stickleback_Anesthesia.qmd
        - 04_Vertebrate_Husbandry/Husbandry_Stickleback_Density_Standards.qmd
        - 04_Vertebrate_Husbandry/Husbandry_Stickleback_Cross.qmd
        - 04_Vertebrate_Husbandry/Husbandry_Stickleback_Dry_Food_Mix.qmd
        - 04_Vertebrate_Husbandry/Husbandry_Stickleback_Testes_Storage.qmd
        - 04_Vertebrate_Husbandry/Husbandry_Stickleback_Sentinel_Fish.qmd
        - 04_Vertebrate_Husbandry/Husbandry_Stickleback_Embryo_Bleaching.qmd
        - 04_Vertebrate_Husbandry/Husbandry_Stickleback_Embryo_and_Larval_Euthanasia.qmd
        - 04_Vertebrate_Husbandry/Husbandry_Syngnathid_wild_fish_introduction.qmd
        - 04_Vertebrate_Husbandry/Husbandry_Syngnathid_Crossing.qmd
        - 04_Vertebrate_Husbandry/Husbandry_Syngnathid_Colony_Maintanence.qmd
        - 04_Vertebrate_Husbandry/Husbandry_Syngnathid_Embryo_and_Larval_Euthanasia.qmd
        - 04_Vertebrate_Husbandry/Husbandry_Syngnathid_Adult_Euthanasia.qmd
        - 04_Vertebrate_Husbandry/Husbandry_Syngnathid_Adult_Anesthesia.qmd

    - part: Part5_Vertebrate_Experiment.qmd
      chapters:
        - 05_Vertebrate_Experiment/VertExperiment_Live_Alizarin_Staining_Syngnathid.qmd
        - 05_Vertebrate_Experiment/VertExperiment_Live_Calcein_Staining_Syngnathid.qmd
        - 05_Vertebrate_Experiment/VertExperiment_Live_Daspei_Staining_Syngnathid.qmd
        - 05_Vertebrate_Experiment/VertExperiment_Live_Fin_Clipping_Syngnathid.qmd
        - 05_Vertebrate_Experiment/VertExperiment_Field_Collection_Syngnathid.qmd
        - 05_Vertebrate_Experiment/VertExperiment_Field_Collection_Stickleback.qmd
        - 05_Vertebrate_Experiment/VertExperiment_Dechorionating_Zebrafish_Embryos.qmd

    - part: Part6_Invertebrate_Husbandry.qmd
      chapters:
        - 06_Invertebrate/Placeholder_Daphnia.qmd
        
    - part: Part7_Common_Recipes.qmd
      chapters:
        - 07_Recipes/Recipe_Husbandry_deitrichs_fix.qmd
        - 07_Recipes/Recipe_Husbandry_embryo_medium.qmd
        - 07_Recipes/Recipe_Husbandry_ginzbergs_ringers.qmd
        - 07_Recipes/Recipe_Husbandry_mesab_stock.qmd
        - 07_Recipes/Recipe_Husbandry_testes_solution.qmd
        
    - part: Part8_Bioinformatic.qmd
      chapters:
        - 08_Bioinformatic/base-R.qmd
  
    - part: Part9_References.qmd
      chapters:      
        - references.qmd
        - notes.qmd 

  appendices:
    - 10_Appendices/appendix_1.qmd
    - 10_Appendices/appendix_2.qmd
  
bibliography: references.bib

format:
  html:
    theme: cosmo
    number-depth: 1
  pdf:
    documentclass: scrreprt
    number-depth: 1
    include-in-header: 
      text: |
        \usepackage{makeidx}
        \makeindex
    include-after-body: 
      text: |
        \printindex
  epub:
    cover-image: images/CreskoLabLogo.png
    number-depth: 2
    
editor: visual

