# Live syngnathid DASPEI staining {#sec-vert_exp_live_daspei_syngnathid}

## Introduction

-   **Purpose**: This procedure describes how to live stain syngnathid with DASPEI.
-   **Procedure Type**: Vert Experimental
-   **Species**:
    -   Bay pipefish, (*Syngnathus leptorhyncus*)
    -   Gulf pipefish (*Syngnathus scovelli*)
-   **Author**: Susie Bassham
-   **Date Created**: October 25, 2021; adapted from DOI: 10.1007/s10162-002-3022-x

## Materials

-   Petri dishes and/or 1 L tanks
-   DASPEI (Sigma Aldrich; cat. D3418)

## Solutions

-   MESAB anesthesia strength {#sec-husbandry_anesth_pipefish}
-   MESAB euthanisia strength {#sec-husbandry_adult_syng_euth}
-   25 ppt Instant Ocean
-   Staining Solution:
    -   0.005% DASPEI in sea water

## Procedure

1.  Stain larvae in Petri dishes and juveniles/adults in 1 L tanks containing stain solution for 5 to 75 min in the dark; stagger so that no fish stain longer than this before imaging. Rinse for 20 to 60 min in container of sea water without DASPEI to reduce background.
2.  Keep fish in the dark as much as is reasonably convenient through procedures. Monitor fish every 15-30 minutes.
3.  Anesthetize until the fish reaches a light plane of anesthesia (i.e. movement has slowed down enough that the fish can be safely handled) and observe/image fluorescence immediately.
4.  After fish has been observed/imaged place in a container of fish water. Monitor fish every 5-10 minutes until the fish is revived. Once fish is revived place back on the fish system and monitor during daily health checks. If the fish is to be fixed for post mortem experiments place fish directly into euthanasia MS222 solution and follow the euthanasia SOP.
5.  Staining solution can be stored at 4C and reused.

## Associated Papers

-   xxx
-   xxx
-   xxx
-   xxx
