# Live syngnathid alizarin staining {#sec-vert_exp-live_alizarin_syngnathid}

## Introduction

-   **Purpose**: This procedure describes how to live stain syngnathid with alizarin.
-   **Procedure Type**: Vert Experimental
-   **Species**:
    -   Bay pipefish, (*Syngnathus leptorhyncus*)
    -   Gulf pipefish (*Syngnathus scovelli*)
-   **Author**: Mark Currey
-   **Date Created**: January 01, 2024

## Materials

-   Large Petri Dish
-   xxx
-   xxx
-   xxx

## Solutions

-   Alizarin stock solutions: 0.5g Alizarin red in 100ml or in 50ml in sterile water (SIGMA cat# A5533 Alizarin Red S, certified).
-   Staining Solution:
    -   25 ppt Instant Ocean
    -   Add 10 ml 0.5% or 1% Alizarin Stock in sterile water for final concentrations of 0.005% or 0.01%.
    -   Adjust to pH 7.5 with NaOH
-   For 50 ml (enough for 100mm diameter petri dish):
    -   49.5 ml Embryo medium
    -   Add 500 µl 0.5% or 1% Alizarin Stock in sterile water
    -   Adjust to pH 7.5 with NaOH
-   MESAB anesthesia strength {#sec-husbandry_anesth_pipefish}
-   MESAB euthanisia strength {#sec-husbandry_adult_syng_euth}

## Procedure

1.  Place fish into a container containing stain for 1-2 hours for larvae to overnight for juveniles or adult fish in the dark. We have found that fish do not experience adverse effects from being exposed to stain. Monitor fish every 30-60 minutes if possible. To de-stain, rinse thoroughly with embryo medium by placing fish into container of embryo medium without stain for 30 minutes; background continues to go down with time. Move on to DASPEI live staining if desired (see DASPEI live staining SOP) or anesthetize until the fish reaches a light plane of anesthesia (i.e. movement has slowed down enough that the fish can be safely handled) and observe/image.
2.  Bone fluorescence will decrease over time, so plan on imaging the same day if possible.
3.  Keep fish in the dark as much as is reasonably convenient.
4.  After fish has been observed/imaged place in a container of fish water. Monitor fish every 5-10 minutes until the fish is revived. Once fish is revived place back on the fish system and monitor during daily health checks. If the fish is to be fixed for post mortem experiments place fish directly into euthanasia MS222 solution and follow {#sec-husbandry_adult_syng_euth}.

## Associated Papers

-   xxx
-   xxx
-   xxx
-   xxx
