# Stickleback Backfilling of Hindbrain Neurons {#sec-vert_exp-hindbrain_backfill}

## Introduction

-   **Purpose**: This procedure describes how to perform backfilling of stickleback hindbrains.
-   **Procedure Type**: Vert Experiment
-   **Species**:
    -   Threespine stickleback, (*Gasterosteus aculeatus*)
-   **Author**: Susie Bassham
-   **Date Created**: January 01, 2020

## Materials

-   Obsidian
-   Rhodamine

## Solutions

-   MS-222 Anesthesia solution {#sec-sb_adult_anesthisia}
-   MS-222 Euthanasia solution {#sec-husb-adutl_sb_euthanasia}
-   Stickleback embryo medium {#sec-general_recipe_embryo_medium}
-   DiO lipophilic carbocyanine dye
-   Antibiotic (Cell Culture anti-biotic/mycotic from Gibco-BRL (15240-096) 100x Concentration)

## Procedure

1.  Sedate Larval fish in MS222 in sterile filtered seawater + antibiotic (Cell Culture anti-biotic/mycotic from Gibco-BRL (15240-096) 100x Concentration).
2.  Use a obsidian glass flake, an extremely sharp scalpel, an incision will be made from the dorsal side, extending ventrally just through the spinal cord.
3.  Use a fine insect pin to apply dried crystals of rhodamine dextran, DiO, or similar reagent to the cut spinal cord.
4.  Continuously sedate larvae. Euthanized with MS222 and fixed 5 to 16 hours after surgery prior to imaging.

## Associated Papers

-   xxx
-   xxx
-   xxx
-   xxx
