# Alcian and Alizarin double stain - No Acid No Pain Double Stain {#sec-vertexp_doublestain}

## Introduction

-   **Purpose**: Effectively stain fixed fish with Alician Blue and Alizarin Red
-   **Procedure Type**: Vertabrate Experiment
-   **Species**:
    -   Threespine stickleback, (*Gasterosteus aculeatus*)
    -   Bay pipefish, (*Syngnathus leptorhyncus*)
    -   Gulf pipefish (*Syngnathus scovelli*)
    -   Zebrafish, (*Danio rerio*)
    - and others
-   **Author**: Macie B. Walker (Adapted by Mark Currey 7/9/13)
-   **Date Created**: 

::: {.callout-warning title="NOTES"}
xxxx
:::

## Purpose: {#purpose .head}

Alcian blue is a basic dye which stains acidic mucopolysaccharides. Traditionally alcian staining has utilized acidic conditions to stain cartilage. As acidic conditions negatively affect bone staining, simultaneous cartilage and bone staining is problematic. Also since acid conditions destroy DNA, embryos to be alcian stained by the acid method & also prepped for DNA have to be dissected into heads for alcians and tails for DNA. This process is laborious. The protocols below use MgCl2 rather than acid to differentiate staining. They have been tested on zebrafish embryos 4-6 dpf and on young adult zebrafish, 6 months old. For zebrafish embryos 4-6 dpf, up to 100 embryos can be stained in a 1.5ml tube, using 1ml of stain/washes per tube. For young adult zebrafish, use 8X volume of stain/washes per volume of fish (roughly 40 ml solution/ 20 fish). All steps are at room temperature, with rocking unless otherwise noted.

### Bone stain is sensitive to changes in protocol: {#bone-stain-is-sensitive-to-changes-in-protocol .subhead2}

It is easy to reduce/lose bone stain. Reduction of bone stain is apparent when certain regions of the bone do not stain well. It is common to have OP staining reduced in skirt region, Mx & den staining reduced or gone. Staining tends to remain in denser regions such as CB5. Overfixation, even by just a few hrs can reduce bone staining. Staining embryos in alizarin overnight vs 30min can reduce bone stain. (Longer is not necessarily better). Bleaching can reduce bone stain, especially if it is not washed out well, which tends to happen if a lot of embryos are stained in one tube. Trypsinizing embryos, even just a little bit, can dramatically reduce bone stain. Detergent (Tween at 0.05%) can also wipe out the bone stain. So, caution: maybe first follow protocol as is, and then make changes to suit your needs.

### DNA preps: {#dna-preps .subhead2}

Rinse out 50% glycerol/0.1%KOH with 2X quick rinses in low TE plus squirt of PBSTw. Sort embryos into 96 well plate, remove excess liquid, and lyse under standard conditions. The tween in PBSTw will help prevent the embryos from getting sticky, but will also remove the bone stain.

### Cartilage only stain: {#cartilage-only-stain .subhead2}

Longer fixes, even 4%PFA overnight, are fine. Cellular detail, including muscles, ligaments, and cartilage nuclei are quite good under normarski.

### Bone only stain: {#bone-only-stain .subhead2}

PFA fixed embryos have decreased bone fluorescence. For better bone fluorescence, fix & stain in 95% ethanol/0.01% alizarin overnight (one step). Do not use MgCl~2~ in washes, and extend washes to 10 mins. Embryos will be soft due to light fix.

For a brief discussion of stain theory describing use of pH and salt to control staining see the web page: <http://stainsfile.info/StainsFile/jindex.html>

------------------------------------------------------------------------

## Materials

-   containers to hold fish and solutions
-   rocker

## Solutions

### Solutions for embryos

- **2% PFA/1X PBS pH 7.5**

  *For 1 ml, add:*
    -   250ul 8% PFA
    -   100ul 10X PBS
    -   650ul water
    -   100mM Tris pH 7.5/10mM MgCl~2~
    
- **0.2% alcian blue/90%ETOH**

::: {.callout-Note title="NOTES"}
Alcian blue will not readily dissolve in 90%ETOH. To make 100 mls add 0.2g alcian blue 8GX powder to 11.2ml 50%ETOH. Warm and occasionally swirl. When all is dissolved add 95% ETOH to 100 ml. Check clarity of solution under a microcope to make sure there are no precipitates. 
:::
 
 
 - **0.04% Alcian/10mM MgCl2 Stain pH 7.5** 
       *Final concentrations:*
      -   0.04% alcian blue
      -   80 % ETOH
      -   100mM Tris pH 7.5
      -   10mM MgCl~2~

      *To make 50 mls, add:*
      -   10ml 0.2% alcian blue in 90% ETOH
      -   5ml 1M Tris pH 7.5
      -   0.5ml 1M MgCl~2~
      -   32.6ml 95% ETOH
      -   1.9ml water

**For Ethanol rehydrations**
    *To make 50 mls of each:*

       **80% ETOH/10mM MgCl~2~**
      -   42.1ml 95% ETOH
      -   5ml 1M Tris pH 7.5
      -   0.5ml 1M MgCl~2~
      -   2.4ml water
      
      **50% ETOH:**
      -   26.3ml 95% ETOH
      -   5ml 1M Tris pH 7.5
      -   18.7ml water
      
      **25% ETOH:**
      -   13.2ml 95% ETOH
      -   5ml 1M Tris pH 7.5
      -   31.8ml water

- **0.5% alizarin red S*

      *To make 50 mls, add:*
      - 0.25g alizarin red S powder 
      - 50 ml water.


- *3% H~2~0~2~/0.5% KOH:*

      - Mix just before using: 0.5ml 6% H~2~0~2~ & 0.5ml 1% KOH (or adjust to desired final volume)
      
- *50% Isopropanol*
      *To make 50 mls, add:*
          - 25 ml H20
          - 25 ml Isopropanol.

## Procedure

      1.	Fix 2% PFA/1XPBS 1 hr.
      
::: {.callout-Note title="NOTES"}
Fixing times can vary depending on the size of the specimen. We have found that for 5-10 mm stickleback and pipefish a fix of 2-3 hours is sufficient.
:::      
    
      2.	Rinse 50% ETOH/water 10 mins.
      3.	Double stain: Add 0.04% Alcian Blue/ 0.01% Alizarin Red S/10mM MgCl2/80% ETOH. Add Alizarin Red just before use. (add 20ul 0.5% alizarin red / 1ml of 0.04% alcian)

::: {.callout-Note title="NOTES"}
With very small specimens it’s very easy to over stain. Check amount of staining every 30 minutes until the desired level of staining has been achieved. 
Important: Store stock as 0.04% Alcian Blue/10mM MgCl2/80% ETOH.
:::       
    
      4.	Rinse 80% ETOH/10mM MgCl2/water 10 mins to overnight.  Cleaner Alcian background with longer rinses.
      5.	Rinse 50% ETOH/water 5 mins.
      6.  Rinse 25% ETOH/water 5 mins.(Can fudge here, just rehydrating)
      7.	Bleach 3% H202/0.5% KOH 10 mins, lids open.
      8.  Rinse with water
      9.  Rinse with 50% Isopropanol
      10.	Store in 50% Isopropanol


##Papers
(Walker, M., Kimmel, C., 2007. A Two-Color Acid-Free Cartilage and Bone Stain For Zebrafish Larvae. Biotechnic & Histochemistry. Vol. 82, No. 1, Pages 23-28.)