# Stickleback Embryo Injections {#sec-vert_exp-embryo_injections}

## Introduction

-   **Purpose**: This procedure describes how to inject embryos with injection rig.
-   **Procedure Type**: Vert Experimental
-   **Species**:
    -   Threespine stickleback, (*Gasterosteus aculeatus*)
-   **Author**: Mark Currey\
-   **Date Created**: January 01, 2024

## Materials

-   Petri dish with specialized trough rig
-   Injection rig

## Solutions

-   Embryo medium

## Procedure:

::: {.callout-note title="background"}
(from: Zebrafish Book 4th addition chp 5) This is an easy method for holding embryos while injecting CRISPR elements, DNA, lineage tracer dyes, etc., without removing their chorions. The embryos are held in wedged-shaped troughs. Each trough can hold approximately 35 embryos (with chorions). Embryos can be aligned by gently tamping them down with forceps. As the pipette penetrates the chorion, the embryo is forced against the rear vertical wall of the trough. The exact positioning of the pipette tip within the embryo is achieved by slight movement of the pipette with a micromanipulator or by movement of the stage. If the pipette tip is thin and long enough, it can be withdrawn from the chorion without dragging the embryo out of the trough. A problem with thin pipettes, however, is that they lack the tensile strength to penetrate the chorion and bend when forced onto the chorion surface. Thicker pipettes do not easily slip out of the chorion, although the embryo can be held with forceps as the pipette is slowly withdrawn.
:::

-   

1.  Injecting:
    1.  Warm the Petri dish to the temperature you prefer for injection (embryos can tolerate 18°C for about 1 hour, and the slower division rate allows more time to inject at the 1 and 2 cell stage).
    2.  Remove the plastic mold.
    3.  Position the dish on a microscope stage and adjust the angle of the pipette so that you can aim directly into the trough.
    4.  Transfer embryos into the troughs.
    5.  Using forceps, align the embryos all in the same orientation. Add enough culture medium so that the level reaches the plastic edges of the slits. Gently tamp the embryos down into the trough.
    6.  Using controls on the micromanipulator, force the pipette through the chorion and the yolk cell, entering the embryonic cell(s) from the yolk cell. (You might prefer to enter the embryonic cell directly; in this case, you would choose a different orientation of the embryo in the trough.)
    7.  As the pipette goes through the yolk, move the Petri dish a bit so that the pipette is close to the plastic cover.
    8.  Inject the desired volume of solution and then withdraw the pipette with a slow steady motion. The embryo will catch on the plastic cover and drop back into the trough.
    9.  Transfer the embryos into a dish with embryo medium and maintain at 20°C for further development.

## Associated Papers

-   xxx
-   xxx
-   xxx
-   xxx
