# Live fin clipping in Stickleback and Pipefish {#sec-vert_exp-live_fin_clipping}

## Introduction

-   **Purpose**: This procedure decribes how to take live fin clips in stickleback and pipefish
-   **Procedure Type**: Vert Experimental
-   **Species**:
    -   Threespine stickleback, (*Gasterosteus aculeatus*)
    -   Bay pipefish, (*Syngnathus leptorhyncus*)
    -   Gulf pipefish (*Syngnathus scovelli*)
-   **Author**: xxx
-   **Date Created**: xxx

## Materials

-   Beakers of system water
-   Forceps and scissors
-   Bucket of ice
-   1.5ml tubes

## Solutions

-   MS-222 Pipefish Anesthesia solution {#sec-husbandry_anesth_pipefish}
-   MS-222 Stickleback Anesthesia solution {#sec-sb_adult_anesthisia}
-   Melafix (antifungal and antibacterial agent)

## Procedure

1.  To minimize fish's exposure to MS-222, do all labeling of tubes and vials prior to fin clipping.
2.  Place fish in beaker containing MS-222 anesthesia dose.

::: {.callout-notes title="NOTES"}
To observe slowed breathing watch the operculum movement. This movement will slow and the fish will turn on its side.
:::

3.  Once the breathing of the fish slows take fish out of water and remove caudal fin - carefully avoiding the peduncle - with scissors and forceps.
4.  Place fin in labeled 1.5 ml tube on ice.
5.  Put fish into clean system water and move gently to force water over gills.
6.  Once fish is revived and swimming upright, put fish into new container with Melafix (diluted in system water according to manufacturer's recommendations) for 15 minutes.
7.  Return fish to aquaculture system.

## Associated Papers

-   xxx
-   xxx
-   xxx
-   xxx
