# Calcein staining {#sec-xxx-xxx}

### *Syngnathid fishes*

## Introduction

-   **Purpose**: This procedure describes how to live stain pipefish with calcein
-   **Procedure Type**: Animal Experimental
-   **Species**:
    -   Bay pipefish, (*Syngnathus leptorhyncus*),
    -   Gulf pipefish (*Syngnathus scovelli*)
-   **Author**: xxx
-   **Date Created**: xxx

::: {.callout-warning title="NOTES"}
xxxx
:::

## Materials:

-   Petri dishes and/or 1 L tanks
-   Calcein (Molecular Probes; cat. C481)

## Solutions:

-   MS-222 Anesthesia solution (see fish anesthesia and euthanasia SOP)?
-   Artificial sea water
-   10% NaOH
-   Stain Solution:
-   0.005 to 0.05% calcein in sea water.
-   Adjust pH to 8.2 with NaOH
-   Make fresh, keep in dark.

## Procedures:

-   Place fish into a container containing stain for 1-2 hours for larvae to overnight for juveniles or adult fish in the dark. We have found that fish do not experience adverse effects from being exposed to stain. Monitor fish every 30-60 minutes if possible. To de-stain, rinse thoroughly with embryo medium by placing fish into container of embryo medium without stain for 30 minutes; background continues to go down with time. Move on to DASPEI live staining if desired (see DASPEI live staining SOP) or anesthetize until the fish reaches a light plane of anesthesia (i.e. movement has slowed down enough that the fish can be safely handled) and observe/image.?
-   Bone fluorescence will decrease over time, so plan on imaging the same day if possible.?
-   Keep fish in the dark as much as is reasonably convenient.?
-   After fish has been observed/imaged place in a container of fish water. Monitor fish every 5-10 minutes until the fish is revived. Once fish is revived place back on the fish system and monitor during daily health checks. If the fish is to be fixed for post mortem experiments place fish directly into euthanasia MS222 solution and follow the euthanasia SOP.

## Associated Papers:
