# Steroid Measurement {#sec-vert_exp-steroid_measure}

## Introduction

-   **Purpose**: This procedure describes the technique of how to measure steroids in water that has been occupied by fish.
-   **Procedure Type**: Vert Experiment
-   **Species**:
    -   Threespine stickleback, (*Gasterosteus aculeatus*),
    -   Bay pipefish, (*Syngnathus leptorhyncus*),
    -   Gulf pipefish (*Syngnathus scovelli*)
    -   Zebrafish, (*Danio rerio*),
-   **Author**: xxx
-   **Date Created**: xxx

## Materials: {#materials .head}

-   150 ml glass beaker
-   C18 solid phase extraction (SPE) cartridges containing octadecylsilane (Sep-pak Plus, Waters Ltd., Watford, UK)

## Solutions

-   5 ml of distilled water
-   5 ml ethyl acetate
-   1 ml of RIA buffer (0.5 M phosphate buffer containing 0.2% bovine serum albumen, 0.8% sodium chloride, 0.03% EDTA and 0.01% sodium azide)
-   ^3^H-labeled steroids for 11-KT are purchased directly from Amersham Biosciences, UK (Scott et al., 2005)

## Procedure

### Water Collection {#water-collection .subhead}

-   The fish is placed in a 150-ml glass beaker with 50 ml of fresh water (the same source as used for aquaria) for 30 min.
-   In the case of male sticklebacks in individual tanks, the beaker is placed on a support in the tank to minimise the potential confinement stress.
-   After the 30-min period the fish is released in its tank.
-   If not able to pump the water sample immediately, pour the conditioned water into a 50-ml polypropylene centrifuge tube and store at 4°C (up to 1hour) or -20°C.

### Steroid Extraction {#steroid-extraction .subhead}

-   Water samples are pumped through C18 solid phase extraction (SPE) cartridges containing octadecylsilane (Sep-pak Plus, Waters Ltd., Watford, UK).
-   The cartridges are first washed with 5 ml of 100% methanol and then 5 ml of distilled water.
-   As the volume of water is small (50ml) no filter is used.
-   The water samples are transferred into 60-ml syringes (BD Plastipak), drawn by vacuum through the cartridges, and 5 ml of distilled water is pushed through the cartridges and blown out.
-   The steroids are extracted with 5 ml ethyl acetate, which was then dried down to dryness under a stream of nitrogen (45°C).
-   Then, 1 ml of RIA buffer (0.5 M phosphate buffer containing 0.2% bovine serum albumen, 0.8% sodium chloride, 0.03% EDTA and 0.01% sodium azide) is added and the tubes stored at -20°C until RIAs.

### Radioimmunoassay {#radioimmunoassay .subhead}

-   ^3^H-labeled steroids for 11-KT are purchased directly from Amersham Biosciences, UK (Scott et al., 2005).
-   Antisera came from previously recorded sources (see (Lower et al., 2004) where the same sort of study was carried out).
-   The RIA procedure has been described previously (Scott et al., 1980; Scott et al., 1984; Scott et al., 1982).
-   Briefly, 100 μl aliquots from the water sample extract or standards are transferred to assay tubes.
-   Labelled steroids and antisera are added in a further 100 μl of assay buffer, and the tubes left to incubate overnight at 4°C.
-   Free and bound labelled steroids are separated with dextran-coated charcoal by centrifugation (2,500 rpm for 12 min at 4ºC).
-   The supernatant is poured into suitable vials and 7 ml of scintillation fluid is added.
-   Each tube is then counted for 5 min in the counter (Beckman LS 6500).
-   The detection limit of the assays varied between 1 and 10 pg/ assay tube (i.e. 10 pg/ 100μl assay buffer).

## Associated Papers

-   LOWER, N., SCOTT, A. P. & MOORE, A. (2004). Release of sex steroids into the water by roach. --- Journal of Fish Biology 64, 16-33.
-   SCOTT, A. P., BYE, V. J., BAYNES, S. M. & SPRINGATE, J. R. C. (1980). Seasonal variations in plasma concentrations of 11-ketotestosterone and testosterone in male rainbow trout, Salmo gairdnerii Richardson. --- Journal of Fish Biology 17, 495-505.
-   SCOTT, A. P., SHELDRICK, E. L. & FLINT, A.P.F. (1982). Measurement of 17a,20b-dihydroxy-4-pregnen-3-one in plasma of trout (Salmo gairdneri Richardson): seasonal changes and response to salmon pituitary extract. --- General and Comparative Endocrinology 46, 444-451
-   SCOTT, A. P., MACKENZIE, D. S. & STACEY, N. E. (1984). Endocrine changes during natural spawning in the white sucker, Catostomus commersoni. II. Steroid hormones. --- General and Comparative Endocrinology 56, 349-359.
-   SCOTT, A. P., PINILLOS, M. L. & HUERTAS, M. (2005). The rate of uptake of sex steroids from water by Tinca tinca is influenced by their affinity for sex steroid binding protein in plasma. --- Journal of Fish Biology 67, 182-200
