# Pipefish backfill labeling if hindbrain neurons {#sec-vert_exp-syngnathid_neuron}

## Introduction

-   **Purpose**: This procedure descibes how to backfill nerons of pipefish.
-   **Procedure Type**: Experimental
-   **Species**:
    -   Bay pipefish, (*Syngnathus leptorhyncus*)
    -   Gulf pipefish (*Syngnathus scovelli*)
-   **Author**: Susie Bassham
-   **Date Created**: xxx

## Materials

-   Antibiotic (Cell Culture anti-biotic/mycotic from Gibco-BRL (15240-096) 100x Concentration) Stickleback embryo medium
-   Obsidian
-   Rhodamine
-   DiO lipophilic carbocyanine dye

## Solutions

-   MS-222 Anesthesia solution {#sec-husbandry_anesth_pipefish}
-   MS-222 Euthanasia solution {#sec-vert_husb-euthanasia_syngnathid}

## Procedure

1.  Sedate Larval fish in MS222 in sterile filtered seawater + antibiotic (Cell Culture anti-biotic/mycotic from Gibco-BRL (15240-096) 100x Concentration).
2.  Use a obsidian glass flake, an extremely sharp scalpel, an incision will be made from the dorsal side, extending ventrally just through the spinal cord.
3.  Use a fine insect pin to apply dried crystals of rhodamine dextran, DiO, or similar reagent to the cut spinal cord.
4.  Continuously sedate larvae. Euthanized with MS222 and fixed 5 to 16 hours after surgery prior to imaging.

## Associated Papers

-   xxx
-   xxx
-   xxx
-   xxx
