# Fin clipping {#sec-vert-fin_clip_syn}

### *Syngnathid fishes*

## Introduction

-   **Purpose**: This procedure describes how to take fin clips from live pipefish.
-   **Procedure Type**: Husbandry
-   **Species**:
    -   Bay pipefish, (*Syngnathus leptorhyncus*),
    -   Gulf pipefish (*Syngnathus scovelli*)
-   **Author**: Mark C. Currey
-   **Date Created**: 06 April 2010

::: {.callout-warning title="xxxx"}
xxxx
:::

## Solutions:

-   MS-222 Anesthesia solution (see fish anesthesia and euthanasia SOP)
-   Melafix (antifungal and antibacterial agent)

## Materials:

-   Beakers of system water
-   Forceps and scissors
-   Bucket of ice
-   1.5ml tubes

## Procedure:

-   To minimize fish?s exposure to MS-222, do all labeling of tubes and vials prior to fin clipping.
-   Place fish in beaker containing MS-222 anesthesia dose in system water (168 mg/L).
-   Once the breathing of the fish slows take fish out of water and remove caudal fin blade ? carefully avoiding the peduncle - with scissors and forceps. Note: To observe slowed breathing watch the operculum movement. This movement will slow and the fish will turn on its side.
-   Place fin in labeled 1.5 ml tube on ice.
-   Put fish into clean system water and move gently to force water over gills.
-   Once fish is revived and swimming upright, put fish into new container with Melafix (diluted in system water according to manufacturer?s recommendations) for 15 minutes.
-   Return fish to aquaculture system.
