# Stickleback wild collections {#sec-vert_exp-stickleback_collections}

## Introduction

-   **Purpose**: This procedure describes how to collect wild threespine stickleback.
-   **Procedure Type**: Field
-   **Species**: Threespine stickleback, (*Gasterosteus aculeatus*)
-   **Author**: Mark Currey
-   **Date Created**: September 10, 2012

## Materials

-   Minnow Traps
-   Field Notebook
-   500 and 1000ml Nalgene bottles
-   Bucket
-   Net
-   Mouse cage
-   Gloves
-   Crossing materials (see stickleback crossing SOP)

::: {.callout-warning title="OPTIONAL"}
-   Waders
-   Kayak
:::

## Solutions

-   95% ETOH
-   Mesab (see fish Euthanasia SOP)

## Procedure

-   **Minnow trap collecting**

    1.  Place traps in areas with cover.

    2.  Tether trap to shore or other non-movable object.

    3.  Leave traps up to but not over 24 hours. Traps may need to be checked more frequently depending on the tidal influence of water body being investigated.

    4.  Pull traps looking for endangered species such as salmonids, Oregon chub, and/or Bull Trout. If an endangered species is noticed open trap under water and release all of the fish.

    5.  If no endangered species are noticed, remove trap from the water and empty contents in a bucket filled 1/3 with water from where the trapping is taking place.

    6.  Remove, count, and record all stickleback and non-stickleback species. This will be used for ODFW reporting at the end of the year.

    7.  Record (in field notebook); collecting location, GPS coordinates, water temp, water type, water condition, substrate condition, vegetation condition, pH (if possible), D.O. (if possible), and other environmental measurements.

::: {.callout-warning title="TRAP PLACEMENT"}
Care should be taken when setting traps in tidally influenced waters as traps that are set above the low water line have the potential to leave fish without water resulting in fish fatality.
:::

-   **Trap Disinfection**:

    1.  Let minnow traps and other collecting equipment air dry for \~ 1 week between collecting locations.
    2.  Further steps may be needed depending on the invasive species encountered. Updates will come soon.

::: {.callout-warning title="TRAP DISINFECTION"}
When trapping between watersheds or between different water bodies within a watershed that ODFW has requested that we disinfect our traps and collecting equipment (see comments for current ODFW fish take permit) please do the following.
:::

-   **Euthanize and Storage of Collected Fish**:

    1.  Euthanize fish using MS222 (see Fish Euthanasia and Anesthesia SOP)
    2.  Collect fish by pouring fish through a net. MS222 can be collected by pouring solution into a secondary container.
    3.  Place fish into a Nalgene container and fill with 95% ETOH. Do not fill bottle over half full with fish as fluids coming out of fish can dilute ETOH to the point that DNA/Tissue degradation can take place.
    4.  Return to lab and assign stock #.
    5.  Alternatively, euthanized fish can be flash frozen by placing in liquid nitrogen and stored in dry ice if high quality DNA is required.

-   **Wild crosses introduction into the lab**:

    -   Crosses fish (see stickleback crossing SOP).

    -   Bleach embryos (see embryo bleaching SOP).

    -   Introduce into fish system (see stickleback crossing SOP).

    -   If embryos are to be fixed and used for investigation fix embryos (see Embryo and larval euthanasia SOP).

## Associated Papers

-   xxx
-   xxx
-   xxx
