# Whole Mount *In situ* {#sec-VertExp_insitu_whole_mount}

## Introduction

-   **Purpose**: This procedure describes how to perform insitus on whole mount embryos.
-   **Procedure Type**: Vert Experiment
-   **Species**:
    - Threespine stickleback, (*Gasterosteus aculeatus*)
    - Bay pipefish, (*Syngnathus leptorhyncus*)
    - Gulf pipefish (*Syngnathus scovelli*)
-   **Author**: Susan Bassham
-   **Date Created**: March 1, 2024

::: {.callout-warning title="Chemical Warning"}
Wear PPE when handling PFA. 
:::

## Materials

-   ice
-   distilled water
-   primary antibody (eg. mouse anti-fish)
-   secondary antibody (eg. goat anti-mouse)
-   tertiary antibody (ie mouse PAP)

## Solutions

-   8% PFA {#sec-general_recipe_8%PFA}
-   BT fix, 4% paraformaldehyde in PBS
-   0.1 M sodium citrate buffer, pH 6.4
-   citrate buffer containing 0.1% sodium azide
-   acetone
-   blocking solution (2% normal goat serum in wash solution \-- PBS
    containing 1% BSA, 1% DMSO, 0.2% triton-X 100)

## Procedure

### Fixation

1. Fix embryos in BT Fix for 4 to 6 hours on ice or at 4°C (see notes
below).

### Modified Antigen-Retrieval

2.  Wash in 0.1 M sodium citrate buffer, pH 6.4, 5 min.
3.  Replace with fresh citrate buffer containing 0.1% sodium azide.
4.  Incubate overnight in 35-40°C water bath. (see note below).


### Acetone Permeabilization

5.  Wash in DW 5 min.
6.  Freeze in acetone at -20°C for 7 min. to permeabilize the tissue
    (see note below).
7.  Wash in DW 5 min.
8.  Wash in 0.1 M citrate buffer 5 min.


## Immuno-histochemistry

9.  Treat with blocking solution (2% normal goat serum in wash solution
    \-- PBS containing 1% BSA, 1% DMSO, 0.2% triton-X 100) to block
    nonspecific binding sites for 30 min.
10.  Treat with primary antibody (eg. mouse anti-fish) diluted in
    blocking solution for 5 hours at RT or overnight at 4°C. A shaker
    may be used to facilitate process.
11.  Wash for about 2 hours with frequent changes of wash solution.
12.  Treat with secondary antibody (eg. goat anti-mouse) diluted in wash
    solution overnight at 4°C or for 5 hours at RT.
13.  Repeat wash step.
14.  If required, treat with tertiary antibody (ie mouse PAP) diluted in
    wash buffer overnight at 4°C or for 5 hours at RT.
15.  Repeat wash step.
16.  If required, develop enzyme-mediated stain.

::: {.callout-note title="Composition of fixative"}
I simultaneously fixed fish in three different aldehyde fixatives: BT
fix, 4% paraformaldehyde in PBS, or 4% paraformaldehyde in 0.1 M
phosphate, pH 7.3. 
- Those fish fixed in 4% paraformaldehyde in phosphate
buffer were poorly and incompletely stained. 
- Those fish fixed in BT fix
or in 4% pf in PBS demonstrated robust staining throughout the head and
trunk of the fish (the staining in the BT-fixed fish may have been
slightly better). 
- I also tested the components in the BT fix. The 4%
sucrose in this fix was required for high-quality staining. 
- In contrast,
the quality of the staining in fish fixed in BT fixative without calcium
was comparable to that of fish fixed in BT fix containing 0.15 mM
calcium chloride.
:::

::: {.callout-note title="Modified Antigen Retrieva"}
- First introduced in the early 1990s, antigen-retrieval methods have been
widely adopted by the clinical community as a way to recover
antigenicity in paraffin sections. 
- Several authors have demonstrated
that heat is one of the most important variables in antigen retrieval
(Brain Res 632, 105-113, 1993; Pathol Int 44, 759-764, 1994; APMIS 102,
295-307, 1994). In my initial experiments, 
- I performed overnight
incubations in citrate buffer at one of 4 temperatures: 4C, room
temperature, 37C or 44C. 
- The 5-day embryos incubated overnight at 4C or
room temperature were poorly and incompletely stained, whereas those
incubated at 37C and 44C were stained robustly throughout the head and
trunk of the fish. 
- However, the background staining in embryos incubated
at 44C was quite high. 
- This background staining was not present in
embryos incubated at 37C. 
- Since these initial experiments, I have been
using embryos incubated overnight at 4C as my negative control. 
- The
quality of the staining in the negative control varies tremendously from
experiment to experiment, whereas there is little or no
experiment-to-experiment variation in the quality of staining in my
positive controls using the above protocol.
:::

##Papers

- Antigen Retrieval Techniques: Immunohistochemistry and Molecular
Morphology*, S-R Shi, J Gu and CR Taylor, Eds., Eaton Publishing,
Natick, MA, 2000.
