# Mesab Stock (EM) {#sec-recipe-mesab}

## Introduction

-   **Purpose**: Recipe for making a mesab stock solution\
-   **Procedure Type**: recipe
-   **Species**:
    -   Threespine stickleback, (*Gasterosteus aculeatus*)
    -   Bay pipefish, (*Syngnathus leptorhyncus*)
    -   Gulf pipefish (*Syngnathus scovelli*)
-   **Author**: Mark Currey
-   **Date Created**: January 1, 2004

::: {.callout-Note title="NOTE"}
Mesab also known as Tricaine must be pharmaceutical-grade. We use tricaine purchased from Pentair, manufactured by Western Chemical and FDA approved. Tricaine (3-amino benzoic acid ethyl lester also called ethyl m-aminoboenzoate) comes in a powdered form. Purchase the smallest amount possible because tricaine expires quickly.
:::

## Materials

-   Mesab, a.k.a. MS222, tricaine, or 3-aminobenzoic acid ethyl ester
-   1 M Tris (pH 9)
-   DD water

## Solutions

-   none

## Procedure

For 1 liter, mix: 1. 4 g tricaine powder 2. 979 ml DD water 3. \~21 ml 1 M Tris (pH 9). 4. Adjust pH to \~7. 5. Aliquot in 50 ml tubes, label with MESAB Stock Solution 4g/L, and store in a -20 freezer.

## Associated Papers

-   xxx
-   xxx
-   xxx
-   xxx
