# Dietrich's Fixative (EM) {#sec-recipe-dietrichs_fix}

## Introduction

-   **Purpose**: Recipe for Dietrich's fixative
-   **Procedure Type**: recipe
-   **Species**:
    -   Threespine stickleback, (*Gasterosteus aculeatus*)
    -   Bay pipefish, (*Syngnathus leptorhyncus*)
    -   Gulf pipefish (*Syngnathus scovelli*)
-   **Author**: Mark Currey
-   **Date Created**: February 29, 2024

::: {.callout-Note title="NOTE"}
When fixing sentinel fish use Dieterich's fixative.
:::

## Materials

-   Ethanol (95%)
-   Formalin (Formaldehyde 37% solution, histological grade, contains 10-15% methanol, Sigma \# F1635)
-   Glacial Acetic Acid
-   Distilled WaterSolutions

## Procedure

1.  Prepare Dietrich's Fixative (100 ml), mix: - 30 ml Ethanol (95%) - 10 ml Formalin (Formaldehyde 37% solution, histological grade, contains 10-15% methanol, Sigma \# F1635) - 2 ml Glacial Acetic Acid - 58 ml Distilled Water
2.  Store fixative at room temperature.

## Associated Papers

-   xxx
-   xxx
-   xxx
-   xxx
