# 2x SSC, 0.2% Tween-20

## Introduction

-   **Purpose**: Recipe for making 50 ml of 2x SSC, 0.2% Tween-20.
-   **Procedure Type**: Recipe
-   **Author**: Micah Woods
-   **Date Created**: March 5, 2024

## Solutions

-   20x SSC (5 ml)
    -   Purchase pre-made from Chem Stores.
-   Tween-20 (100 ul)
    -   Located in the chemical cabinet on the "Oxidizers A-Z" shelf. 
-   Nanopure water
    -   Located in the Nalgene at the north sink. 

## Materials

-   50 ml Falcon tube
-   Pipettes
-   Pipette tips

## Procedure

1.  Fill the 50 ml Falcon tube with 5 ml of 20x SSC.

2.  Add 100 ul of Tween-20 to the tube 

    ::: {.callout-important title="NOTE"}
    Tween-20 is very thick solution, which can make it challenging to pipet. Push the pipette to the first stop, place the pipette tip in the Tween-20, and wait at least 10 seconds for the Tween-20 to fill the pipette tip. Due to its high viscosity, the Tween-20 will take longer to fill the pipette tip compared to less viscous liquids. Once the pipette tip is full, slowly dispense the Tween-20 into the tube.
    :::

3.  Fill tube to 50 ml with nanopure water.  

4.  Mix the solution by gently inverting the tube a few times. Store at room temperature.  

## Associated Papers

-   x
-   x
-   x