# Fake Hyb

## Introduction

-   **Purpose**: Recipe for making 200 ml of Fake Hyb.
-   **Procedure Type**: Recipe
-   **Author**: Micah Woods
-   **Date Created**: March 5, 2024

## Solutions

-   100% formamide (100 ml)
    -   Located in the "Cruella Cooper" refrigerator. 
-   10x SSC (50 ml)
    -   Purchase pre-made from Chem Stores. 
-   Tween-20 (400 ul)
    -   Located in the chemical cabinet on the "Oxidizers A-Z" shelf.
-   1M citric acid (35 g)
    -   Located in the chemical cabinet on the "Acid and Base Incompatibles A-Z" shelf 
-   Nanopure water
    -   Located in the Nalgene at the north sink. 

## Materials

-   200 ml glass Pyrex jar
-   4 50 ml plastic Falcon tubes
-   Pipettess
-   Pipette tips
-   Fume hood
-   Scale
-   Weigh paper

## Procedure

::: {.callout-important title="IMPORTANT"}
Formamide can be harmful to your health, so this procedure should be performed under the fume hood.
:::

1.  Warm the 100% formamide to room temperature.

2.  Add 100 ml of 100% formamide to the 200 ml glass Pyrex jar.

3.  Add 50 ml of 10x SSC to the jar.

4.  Add 400 ul Tween-20 the the jar.

    ::: {.callout-important title="NOTE"}
    Tween-20 is very thick solution, which can make it challenging to pipet. Push the pipette to the first stop, place the pipette tip in the Tween-20, and wait at least 10 seconds for the Tween-20 to fill the pipette tip. Due to its high viscosity, the Tween-20 will take longer to fill the pipette tip compared to less viscous liquids. Once the pipette tip is full, slowly dispense the Tween-20 into the jar. If pipetting 400 ul of Tween-20 is too difficult, you can instead make a 20% Tween-20 dilution with Tween-20 and nanopure water, and add 2 ml of the 20% Tween-20 to the jar.
    :::

5.  Weigh out 0.35 g of 1M citric acid, and add to the jar.

6.  Fill jar to 200 ml with nanopure water.

7.  Mix the solution by gently inverting the jar a few times.

8.  This recipe makes 200 ml of Fake Hyb. Aliquot the Fake Hyb into 4 50 ml Falcon tubes and store at -20°C.

9.  When you are ready to use the Fake Hyb in the future, melt one of the 50 ml tubes in the water bath or by letting it sit at room temperature. Once melted, mix by inversion to ensure the solution is homogenized, and return it to the -20°C freezer once you are finished.

## Associated Papers

-   x
-   x
-   x
