# Disposing of Hazardous Waste {#sec-general-hazard_waste}

## Introduction

-   **Purpose**: This procedure provides a guideline of how to store and get rid of various forms of hazardous waste (HW) that are produced in the Cresko Lab.
-   **Procedure Type**: General Lab
-   **Author**: Mark Currey
-   **Date Created**: July 30, 2022

## Materials

-   xxx
-   xxx
-   xxx
-   xxx

## Solutions

-   xxx
-   xxx
-   xxx

## Procedure

::: {.callout-important title="IMPORTANT"}
ALL CONTAINERS USED TO HOUSE HAZARDOUS WASTE NEED TO BE LABELED WITH CONTENTS, DATE, AND OWNER.
:::

1.  **Common streams of HW**: Paraformaldehyde (PFA), alcohol (ETOH, methanol, isopropanol, etc), and common kit waste.
    1.  Procedure: Collect these waste streams separately. They can be collected locally (e.g. small containers on lab bench) and then put into the common large carboy for pickup.
    2.  Pick up: Every two weeks a lab assistant will assess if common collections need to be picked up. If so, they will initiate a pick up via EHS. https://safety.uoregon.edu/hazardous-materials
2.  **Exotic or nasty HW**: Trizol, phenol, chloroform, formamide, etc…
    1.  Procedure: Researchers are responsible for communicating with the lab assistant as to how these materials will be temporarily stored and the periodicity of disposal. As an example, if DNA extractions are being done with Trizol, solid (e.g. tips and tubes) that come into contact with this reagent and used reagent will be collected in the hood.
    2.  Pick up: Once the extractions are done or after two weeks (whichever is first) a “pick up” will be initiated with EHS. https://safety.uoregon.edu/hazardous-materials

## Associated Papers

-   xxx
-   xxx
-   xxx
