# Gel electrophoresis tips

## Introduction

-   **Purpose**: To help members of the laboratory run the perfect gels - every time.
-   **Procedure Type**: Molecular
-   **Species**: N/A
-   **Authors**
    -   Susan Bassham

The effect of electrophoresis is to separate DNA fragments by size in an agarose matrix and buffer using an electrical current. DNA is negatively charged and will migrate toward the positive pole. Many parameters can affect how the DNA moves through the gel: buffer composition, voltage, length of the gel, percentage of agarose in the gel (in other words, the density of the gel matrix), presence of salt in the DNA, protein bound to DNA, and other factors. Some of these conditions also affect which size ranges of DNA will effectively be "resolved" (i.e., separated enough from one another so you can see them as distinct fragment sizes). "Safeview" is a dye we use in the gel that fluoresces under UV or blue light when bound to DNA, allowing us to see and photograph it when viewed through a special orange filter to cut out the background light. The research goals of using electrophoresis might include:

-   measuring the size of fragments in a DNA sample such as the products of PCR or assessing the intactness of the purified DNA from a tissue extraction
-   separating fragments from one another so that a particular amplicon or size range of DNA can be purified out of the gel for other downstream applications (such as for cloning a PCR fragment for making probes or for Sanger sequencing, or for size selecting a smear of fragments for making a RAD library) while excluding the other fragment sizes
-   checking for the presence or absence of a particular product of PCR as in a screen for orientation of a cloned fragment in a plasmid present in different bacterial colonies, a screen for an insertion in a transgenic animal, a screen to determine the genetic sex or the mitotype of a fish.

## Common Mistakes

::: callout-warning
These common mistakes will give you a big headache when trying to run gels
:::

-   **Boiling over the agarose when making a gel**.

    -   *Result*: failure to monitor the agarose when you are trying to dissolve it in the microwave can easily cause it to boil over because powdered substances create a lot of "nodes of nucleation" for bubbles to form. This is especially easy to accidentally do with higher percentages of agarose. It wastes expensive agarose and creates a mess in the microwave. What remains in the bottle will be of an indeterminate percentage/gel stiffness.

-   **Not making sure the tape is adhering well to the mold before casting a gel**.

    -   *Result*: liquid agarose will leak out causing a mess and reagent waste. Make sure the mold is dry beforehand, and use the back edge of a comb, e.g., to run across the tape and make sure it has firm contact.

-   **Positioning the comb teeth too close to one side or to the bottom of the mold when setting up for pouring a gel**.

    -   *Result*: the bottoms (or that side) of wells may be torn when the comb is pulled out, causing the loaded samples to leak out into the buffer during gel loading. Note: even when the comb teeth are not too close to the bottom, low percentage gels are soft and will benefit from having the comb pulled while submerged in the tank - otherwise the suction created by surface tension between the comb plastic and the agarose as you pull up on the comb can tear the bottoms out of the wells, causing loss of samples during loading.

-   **Not using the right % of agarose for your DNA size range of interest**.

    -   *Result*: bands you care about won't resolve optimally (i.e., you might not be able to accurately measure the sizes of your bands and might not be able to tell if something is one band or multiple bands). Pour a higher percentage gel to resolve large fragments (e.g. less than 1%) or a lower percentage gel (i.e. between 1 and 4%) to resolve small to very small ones, depending on your needs/expectations for what size bands you will see, how many of them, or how important it is to accurately estimate their sizes.

-   **Not homogeneously mixing the Safeview into the agarose before pouring**.

    -   *Result*: DNA might not be visible in all parts of the gel.

-   **Over-cooling the agarose before pouring**.

    -   *Result*: Safeview will not be evenly distributed in the gel, and/or the gel have lumps and not be of uniform thickness because some of the agarose will have already started polymerizing.

-   **Running a gel with a lot of bubbles in it**.

    -   *Result*: DNA migration can be impeded/distorted by bubbles in the gel. Usually as a gel is cooling, bubbles will migrate to the top where (usually) they will be out of the path of the DNA unless the DNA volume fills the wells to the top. But bubbles can sometimes occur deeper in the gel -- particularly in a very high % agarose gel. Try to nudge bubbles out of the way before the gel solidifies, either by raking them with a comb that is not on a holder or nudging individual bubbles with a pipette tip before the gel congeals. If the gel is already solid, avoid loading in lanes that will run across a bubble.

-   **Running a gel that wasn't mixed homogeneously before pouring in the mold.**

    -   *Result*: there will be lumps in the gel of more dense agarose that will cause distortion of how the DNA migrates.

-   **Accidentally contacting the agarose with a pipette tip**.

    -   *Result*: the bottom or side of the well can become perforated, causing the sample to leak out the bottom or into the next well. If the tip is pressed against the agarose, the sample can be forcefully and suddenly expelled and blast out of the well.

-   **Overloading the wells with too much sample volume**.

    -   *Result*: samples can become cross-contaminated by DNA from adjacent wells.

-   **Overloading the lane with too much DNA**.

    -   *Result*: DNA can become retarded during running and the apparent size will not be accurately gauged by the ladder.

-   **Forgetting to load a DNA ladder**.

    -   *Result*: you won't know if your DNA bands are the right size when you look at and photograph your gel.

-   **Not using gel loading mix in the DNA or using ladder that isn't premixed with gel loading mix**.

    -   *Result*: The DNA or ladder (which is also DNA) will be lost mostly during loading without the gel loading mix that makes it sink to the bottom of the wells in the gel and stay there while you are loading. Both your samples and the ladder are DNA in an aqueous solution that is about the same density as the buffer (usually) -- therefore they both should have gel loading mix in them in order to be denser than the tank buffer. The gel loading mix also includes convenient, charged dyes that migrate at different rates to help you see that your gel is running and how far it has progressed. The gel loading mix types only really matter if one type happens to have a dye that migrates exactly like your band of interest - in that case, you may want to switch to a different mix so that the dye doesn't block the fluorescence of your band during visualization.

-   **Not thoroughly mixing gel loading mix into your DNA before loading**.

    -   *Result*: you could lose part of your DNA to floating out of the well during loading. (This can also happen if there are other reasons your DNA is not very dense, such as if there is residual ethanol in it from preceding processing. In that case, you will see your DNA rapidly floating up to the surface as soon as you start expelling it from the tip).

-   **Adding premixed DNA ladder to your samples instead of gel loading mix**.

    -   *Result*: ladder will appear in every lane, obscuring your bands and wasting expensive ladder.

-   **Forgetting to start the current on your loaded gel**.

    -   *Result*: DNA will diffuse both out of the wells and into the gel in all directions causing loss of some of the DNA and blurriness of the remaining DNA once the gel is run. Diffusion can also happen if it takes a long time to load the gel. If there are a great number of samples to load -- such as in a two- or three-comb gel, it is often best to load one tier and run the gel for 5 minutes so the DNA enters the gel and diffuses more slowly before moving on to load the next tier. Diffusion can happen more quickly if the buffer is warm from a previous run. If the buffer is warm, replace it before trying to load another gel in the same box.

-   **Not keeping track of the order of sample loading**.

    -   *Result*: you won't know which lane corresponds to which sample. This can happen, for example, when loading samples from a strip of PCR tubes, where their order can accidentally be rotated 180 degrees, or when loading from a PCR plate, where the plate orientation can be rotated 180 or 90 degrees (e.g., wells are loaded with respect to rows versus columns).

-   **Running your gel backwards by accidentally reversing the positive and negative electrodes**.

    -   *Result*, your DNA will migrate out of the end of the gel nearest the wells (the "top" of the gel) and be lost into the tank buffer. Always check that your electrodes are hooked up to the correct leads relative to the terminals at the power source, that your gel is oriented so that the DNA will run toward the positive pole. If you have already loaded your gel in the wrong orientation, do not lift the gel out of the tank, but just reverse the leads (red to black) to correct the current. Remember that DNA is negatively charged and will run to the positive (red) pole. When you start the current, the negative electrode (anode) at the well end of the gel should be making noticeably more bubbles than the positive electrode (cathode) at the bottom end of the gel. That's because electrolysis of water (H2O) will produce twice as much free hydrogen at the anode than the cathode makes free oxygen. Making a habit of checking that tells you two things: that current is really flowing and that you do have the right orientation of poles.

-   **Running a gel at too low a voltage**.

    -   *Result*: low molecular weight bands may look fuzzy and faint because they will be diffusing in random directions as they migrate.

-   **Running DNA that is too salty - e.g., DNA in Phusion buffer or in NEB restriction buffer 3 (or 3.1) etc.**

    -   *Result*: a "salt front" will form where DNA in those salty buffers will be slowed ("retarded") relative to the ladder, making the ladder a useless measure of the actual size of the DNA. Bands will be compressed at a "front" and will be a weird shape like a smile or a frown rather than a straight band.

    -   If you know your DNA is in a salty buffer, you can remove this problem by cleaning the DNA first (i.e., via a cleanup column or with paramagnetic beads), or you can mitigate the problem by diluting only a few microliters (e.g. 5 µl) of your DNA into water and gel loading mix before loading (assuming you have a high enough concentration of DNA that it can still be seen if you load only a small fraction of it).

-   **Running a gel made up in a different buffer (or different concentration of buffer) than the buffer in the gel tank; this includes using old buffer that has been evaporating in the tank through multiple runs or over time**.

    -   *Result*: bands will not migrate as expected. "Fronts" may form where the leading edge of the migrating DNA is compressed.

-   **Losing your gel of the end of the gel mold when you are taking it out of the tank**.

    -   *Result*: the gel could shatter and be unsalvageable. Solution: transport gels in a dish and be especially careful when moving flabby, low percentage agarose gels (under 1%).

## Potentially dangerous and/or destructive mistakes:

::: callout-warning
**Running gels is so standard in a laboratory that we can take if for granted, but these mistakes can be costly in terms of ruining a gel at best, or posing human safety risks at worst**
:::

-   **Heating a bottle with a lid on it**.

    -   Result: possible explosion. Just leave the lid off when heating agarose.

-   **Adding Safeview to molten agarose that is too hot**.

    -   Result: much of the Safeview will be degraded by heat, causing your DNA to be hard to see or image. **The plastic gel mold could be permanently warped if the agarose is too hot.** The tape may fail, causing a mess in the fume hood and reagent wastage. A swirled bottle should be just comfortable (70 degrees C or a bit less).

-   **Running a gel at too high a voltage**.

    -   Result: **buffer could overheat during running and permanently warp the plastic of the gel box.** Bands might look smear and not be well resolved.

-   **Dissolving agarose in water instead of electrophoresis buffer or putting water in the electrophoresis tank instead of buffer**.

    -   Result - total failure for DNA to migrate into the gel, loss of samples. **If there is only water and not buffer in the tank, it could overheat and permanently warp the plastic of the gel box.**

-   **Over-running your gel**.

    -   Result: the DNA might run off the bottom of the gel and be lost. If you had more than one tier of wells in the gel, the DNA in the top tier will run into the zone of the next tier down, causing distortion and blurriness of the bands as they cross the wells of the lower tier and creating confusion in interpretation because very small fragments from the top tier will be overlapping very large fragments of the lower tier. If the gel runs for a long time, the **buffer could overheat and permanently warp the plastic of the gel box.**

## Conscietiousness

::: callout-warning
We all work in our laboratory together. Please think of your labmates when you are done running your gel.
:::

Please really clean the gel molds and combs after use. The next person shouldn't have to fish another lab mate's combs and molds out of the sink and clean and dry them before they can pour their gel. After pulling combs from a polymerized gel, make sure to really rub them under a flow of water; a skin of polymerized agarose left on the combs (higher percentages of agarose are especially prone to this) will mean the next person has to clean this off before they can pour a gel. Likewise, make sure the gel melting bottle is rinsed immediately after you pour your gel. If residual agarose is allowed to dry in the bottle, it can create an almost insoluble blob in the gel of the next person to use the bottle. If you see that some of your agarose has polymerized in the bottle, add water to the bottle and microwave it for a few minutes to dissolve and discard the residue.
