# Artemia Decapsulation {#sec-vert_husb-artemia}

## Introduction

-   **Purpose**: This procedure describes standard practices for decapsulating brine shrimp. Although brine shrimp can be hatched, collected and then fed to fish, the cysts are often hard to separate from the newly hatched brine shrimp and can be ingested by stickleback and pipefish. To reduce this phenomenon we can decapsulate brine shrimp in advance, and then leave them in a suspended state in the freezer for an extended period of time (\~ xxx weeks) before they are hatched.
-   **Procedure Type**: Husbandry
-   **Species**:
    -   Threespine stickleback, (*Gasterosteus aculeatus*),
    -   Gulf pipefish (*Syngnathus scovelli*)
-   **Authors**
    -   Mark C. Currey

## Materials:

-   15 oz can of dried Artemia cysts (approximately 430 g)
-   4.3 L \~6% laundry grade bleach
-   Rock Salt (NaCl)
-   125 ml 40% Lye (NaOH) solution
-   30.0 g Sodium thiosulfate (Na\_{2}S\_{2}O\_{3})
-   16 L Hatching Cone with aeration
-   125 ?m mesh bag (Aquatic Eco-Systems PMB3, 125 micron x 18")
-   Several 3-5 L beakers
-   (1-2) Squirt bottles - squeeze type

## Solutions:

::: {.callout-warning title="Be ready"}
Solutions should be prepared in advance.
:::

-   Bleach, \~6% laundry grade
    -   25 ppt Salt Solution
    -   Combine: 50 g Rock Salt (NaCl) To 2.0 L with tap water
    -   Stir to dissolve completely.
-   40% Lye (NaOH) solution
    -   Combine: 200 g Lye (NaOH) To 500 mL with tap water
    -   Stir to dissolve completely.
    -   Store in refrigerator (4°C)
-   Buffered Salt Solution
    -   Combine: 2L, 25 ppt Salt Solution
    -   125 mL 40% Lye Solution, pre-chilled to 4°C
-   1.0% Sodium Thiosulfate
    -   Combine: 30 g sodium thiosulfate To 3.0 L with tap water
    -   Stir to dissolve.
-   Saturated Brine
    -   Combine: \~25g Rock Salt to 4.0 L with tap water
    -   Aerate to dissolve.

## Procedure:

1.  **Cyst hydration**: Hydrate one full can of dried cyst in 5 L of tap water in a hatching cone with aeration for 1 hour at room temp. Examine the cyst under a dissecting scope with top lighting before proceeding. Dry cysts are dimpled, resembling a deflated basketball, whereas fully hydrated cysts are completely spherical in shape. The cysts must be fully hydrated prior to the de-capsulation step. If cysts are not completely spherical after 1 hour, continue the hydration process (for a maximum of 2 hours), checking the progress of the cysts under a microscope every 15 min.

2.  **Filter and rinse cysts**: Collect the hydrated cyst in a 125 um mesh bag and rinse with cool tap water.

3.  **Transfer cysts back to the cone**: Add the Buffered Salt Solution to the cone and aerate (save back a filled squirt bottle of salt solution to help transfer cysts to cone). Transfer cysts into cone.

4.  **De-capsulation**: Add the bleach (4.3 L) to the cone and continue aeration. Watch the cysts turn from brown to grey to orange, When the cysts are 90% orange, stop the reaction by quickly siphoning the cysts through a 125 um mesh bag and rinsing well with cool tap water.

5.  **Neutralization residual chlorine**: To neutralize any residual chlorine transfer the mesh bag to a clean 4 L beaker and pour the 1.0% Sodium Thiosulfate (3L) into the bag. Soak the cysts in the sodium thiosulfate solution for \~1 min, then rinse the cysts with de-ionized tap water. Rinse until discharge turns clear.

6.  **Dehydration for long-term storage**: Transfer the cysts back to the cone with 4 L of saturated brine and aerate until salt is dissolved. Transfer dehydrated cyst to (5 or 6) 1 L Nalgene bottles filled with 200 - 300 grams of salt. Add enough salt so that it does not dissolve when de-capsulated brine is added. Fill the bottles with de-capsulated brine. Store in refrigerator. The de-capsulated brine will store for at least 1 month. Hatch brine as you would capsulated brine (see Hatching and Feeding Brine SOP).
