# Syngnathid Euthanasia {#sec-vert_husb-euthanasia_syngnathid}

## Introduction

-   **Purpose**: This procedure describes best practices for euthanizing embryonic and larval pipefish
-   **Procedure Type**: Vertebrate Husbandry
-   **Species**:
    -   Bay pipefish, (*Syngnathus leptorhyncus*),
    -   Gulf pipefish (*Syngnathus scovelli*)
-   **Author**: xxx
-   **Date Created**: xxx

::: {.callout-warning title="NOTES"}
xxxx
:::

## Materials

-   Euthanasia strength Mesab (see above)
-   Container to hold fish while being euthanized.
-   Post mortem fixing equipment
-   Morgue

## Solutions

-   MS-222 Stock solution of (4g/L, From Zebrafish Book 4th edition)??
    -   Tricaine must be pharmaceutical-grade
    -   We use tricaine purchased from Pentair, manufactured by Western Chemical and FDA approved.
    -   Tricaine (3-amino benzoic acid ethyl lester also called ethyl m-aminoboenzoate) comes in a powdered form.
    -   Purchase the smallest amount possible because tricaine expires quickly.
-   Mesab Stock Solution (4g/L) (tris buffered):
    -   4 g tricaine powder
    -   979 ml DD water
    -   \~21 ml 1 M Tris (pH 9).
    -   Adjust pH to \~7.
    -   Aliquot in 50ml tubes, label with MESAB Stock
    -   Solution 4g/L, and store in a -20 freezer.
    -   This makes 1 liter of solution.
-   Euthanasia Solution (300 mg/L):
    -   Make a solution of tris buffered Stock Solution as described above.
    -   (Or obtain an aliquot from the freezer)
    -   Combine 7.5ml of stock solution into 100 ml of fish water.

## Procedure

-   Procedure for embryo euthanasia:

    -   Place embryos into a MS-222 euthanasia solution.
    -   Leave embryos in solution until movement has stopped, \~ 10 minutes.
    -   If fish is to be used for experiments, proceed with fixation or preparation for the experiment.
    -   If the fish are to be disposed of, place embryo in 95% ETOH for 5 minutes and then into morgue for disposal.

::: {.callout-warning title="NOTES"}
This last step is necessary as a startle response is not obvious in unhatched fish
:::

-   Procedure for larval euthanasia:

    -   Place larva into a MS-222 euthanasia solution.
    -   Wait 10 minutes and perform a tap test to look for a startle response.
    -   If there is a response wait 5 minutes and repeat startle response test.
    -   Repeat this step every 5 minutes as needed.
    -   If there is no response move to fixing for post mortem experiments or place in morgue.
