# Stickleback Dry Fish Food Mix {#sec-recipe-dry_fish_food}

## Introduction

-   **Purpose**: This procedure describes standard practices for mixing of dry food to feed all life stages of threespine stickleback in the Pacific Stickleback Facility.
-   **Procedure Type**: Husbandry
-   **Species**:
    -   Threespine stickleback, (*Gasterosteus aculeatus*)
-   **Author**: Mark Currey
-   **Date Created**: August 25, 2014; updated January 26, 2023 by Mark Currey

## Materials

-   Plastic measuring cup
-   Clean food container

## Solutions

- none

## Procedure

::: {.callout-warning title="NOTES"}
At each new mixing of dry food (approximately once per week) food containers will be cleaned (washed in the dish washer) and spoons cleaned with 70% ETOH. The beaker that holds feeding spoons will also be replaced with clean beaker.
:::

1.  Mix equal parts of the following, store at 4C in fish facility food fridge. Label with an expiration date of 1 month from mixing.

**Fry Mix**:
        1.  100-200 micron golden pearls
        2.  Ziegler AP100
        
**Juvenile Mix**: (label with a yellow dot or yellow tape)
        1.  Aquanix cool mix flakes (or other flake food)
        2.  200-300 micron golden pearls
        3.  Otohime C1 pellets
        
**Adult Mix**:
        1.  Otohime S1
        2.  Ziegler zebrafish diet
        3.  Hikari micro pellet
        4.  Golden pearls 500-800 micron
        5.  Aquanix cool mix flakes (or other flake food)

::: {.callout-note title="NOTES"}
If we are out of one of the types of food it is ok to omite it from the mix. 
:::

## Associated Papers

-   xxx
-   xxx
-   xxx
-   xxx
