# Stickleback Adult Euthanasia {#sec-husbandry-adutl_sb_euthanasia}

## Introduction

-   **Purpose**: This procedure describes best practices for euthanizing adult threespine stickleback.
-   **Procedure Type**: Husbandry
-   **Species**:
    -   Threespine stickleback, (*Gasterosteus aculeatus*)
-   **Author**: Mark Currey
-   **Date Created**: May 6, 2008; revised November 29, 2017 and 2023 by Mark Currey

## Materials

-   Euthanasia strength Mesab (see below)
-   Container to hold fish while being euthanized.
-   Post mortem fixing equipment
-   Morgue

## Solutions

::: {.callout-warning title="NOTES"}
```         
Tricaine must be pharmaceutical-grade. We use tricaine purchased from Pentair, manufactured by Western Chemical and FDA approved. Tricaine (3-amino benzoic acid ethyl lester also called ethyl m-aminoboenzoate) comes in a powdered form. Purchase the smallest amount possible because tricaine expires quickly.
```
:::

-   **Mesab Stock Solution (4g/L From Zebrafish Book 4th edition) (tris buffered)**:

    -   4 g tricaine powder
    -   979 ml DD water
    -   \~21 ml 1 M Tris (pH 9).
    -   Adjust pH to \~7.
    -   Aliquot in 50ml tubes, label with MESAB Stock Solution 4g/L, and store in a -20 freezer.
    -   This makes 1 liter of solution.

-   **Euthanasia Solution (300 mg/L)**:

    -   Make a solution of tris buffered **Stock Solution** as described above. (Or obtain an aliquot from the freezer)
    -   Make a solution of 3.0 ppt Instant Ocean by adding 0.3 grams of Instant Ocean to 100 ml of DD water.
    -   Combine 7.5ml of stock solution into 100 ml of 3 ppt Instant Ocean.
    -   Store solution in an amber bottle to protect it from light and add mixed and expiration dates (6 months after being mixed) to the bottle.

## Procedure

1.  Place fish in mesab and wait 10 minutes.
2.  **Describe how death will be confirmed**:
    -   Ten minutes after opercular movement a tap test will be performed by gently tapping on the table next to the container holding the fish. If the fish is still alive this will trigger a startle response, wait 5 more minutes and repeat tap test. If no response, proceed to fixing for post mortem experiments or place fish in the morgue.

## Associated Papers

-   xxx
-   xxx
-   xxx
-   xxx
