# Weekend Stickleback and Pipefish Feeding and Health Checks {#sec-husbandry-weekend_feeding}

## Introduction

-   **Purpose**: This procedure describes how to conduct weekend feedings and health checks for stickleback and pipefish
-   **Procedure Type**: Husbandry
-   **Species**:
    -   Threespine stickleback, (*Gasterosteus aculeatus*)
    -   Gulf pipefish (*Syngnathus scovelli*)
-   **Author**: Mark Currey
-   **Date Created**: December 15, 2023; modified January 2, 2023 by Micah Woods

## Materials

-   Adult stickleback food
-   Juvenile stickleback food
-   Brine shrimp
-   Squirt bottle
-   De-capsulated brine shrimp
-   Rock salt
-   105 μm mesh shrimp collector
-   Baking soda
-   Frozen mysids
-   1000 ml beaker labeled "Pipefish Only"
-   Net
-   Container to hold fish while being euthanized
-   Postmortem fixing equipment
-   Morgue

## Solutions

-   Euthanasia strength Mesab (located in Mark's fridge in 324 Pacific)

## Procedure

::: {.callout-warning title="NOTES"}
Fish only need to be fed once per day on weekends. Ideally, fish will be fed on weekends around noon since they only receive one feeding, but this time can be flexible to accommodate weekend feeders? schedules.
:::

1.  **Conduct health checks** of all fish in Winter Room and Summer Room according to the steps described in "Husbandry_Health_Check_SOP".

2.  Prepare brine cone for feeding by following the steps described in "Husbandry_Hatching_Feeding_BrineShrimp_SOP".

::: {.callout-warning title="NOTES"}
Since fish are only fed once per day on weekends, use the entire brine cone to feed fish.
:::

3.  **Feed Stickleback**

    1.  Winter Room
        -   20g tanks
            1.  Feed 1 scoop of adult stickleback food.
    2.  Summer Room
        -   20g tanks
            1.  Feed 1 scoop of adult stickleback food.
        -   4.5 and 10.5 liter tanks
            1.  **Larval** (red tags): feed small squirt of brine shrimp.
            2.  **Juvenile** (green and blue tags): feed half of a scoop of juvenile food.

    ::: {.callout-warning title="NOTES"}
    If there is not sufficient adult or juvenile food to conduct feedings, see "Stickleback_Dry_Food_Mix_SOP" for instructions on making more food.
    :::

4.  Feed Pipefish

    1.  Summer Room

        -   20g tanks (adults and juveniles)

            1.  **Adults**: feed frozen mysids

            ::: {.callout-warning title="NOTE FOR PREPARING AND FEEDING FROZEN MYSIDS"}
            Partially fill the 1000 ml beaker labeled "Pipefish Only" located on the pipefish rack with pipefish water. Place a dime sized piece of frozen mysids (bottom shelf in freezer) in the beaker with water, and swirl water to thaw mysids. Once thawed, feed to the adult pipefish.
            :::

            2.  **Juveniles**: feed squirt of brine shrimp.

        -   10.5 liter tanks (mysids, pregnant males, and juvenile pipefish)

            1.  **Juvenile pipefish/mysids**: feed small squirt of brine shrimp.

::: {.callout-warning title="NOTES"}
Please move any male that has given birth into a community (20g) adult pipefish tank
:::

5.  Reset brine shrimp cone according to steps described in "Husbandry_Hatching_Feeding_BrineShrimp_SOP".

## Associated Papers

-   xxx
-   xxx
-   xxx
-   xxx
