# Stickleback Density Standards {#sec-husbandry-stickle_density}

## Introduction

-   **Purpose**: This document describes stickleback and pipefish density standards that are used in the Cresko Lab.
-   **Procedure Type**: Husbandry
-   **Species**:
    -   Threespine stickleback, (*Gasterosteus aculeatus*)
    -   Gulf pipefish (*Syngnathus scovelli*)
-   **Author**: Mark Currey\
-   **Date Created**: January 01, 2020, updated February 05, 2024

## Materials

-   N/A

## Solutions

-   N/A

## Procedure:

::: {.callout-note title="NOTES"}
-   Fry and early juveniles stickleback are kept in short day conditions 12 hours of light/day
-   Adult stickleback are kept in the long day room with 12 hours of light/day.
-   All pipefish are kept in the long day room with 12 hours of light/day.
-   These standards for fish densities are what we in the Cresko lab have determined optimal after 20 years of keeping threespine stickleback and 8 years of keeping pipefish in recirculating aquaculture systems.
:::

### Stickleback Fry (9dpf - 2 months)

-   Fry are kept in 4.5 L tanks at an ideal density of 20 fish per container.
-   Fry can be kept in densities of up to 40 fish per tank.
-   If fish densities are near 40 per tank fish are transferred or thinned after 1 month of age.

### Stickleback Juveniles (2 months - 3 months) Early Grow Out

-   Juvenile fish are transferred from fry tanks into 10.5 L tanks and kept at a density of 20 fish per container.

## Stickleback post-Juvenile (3 months - 1 year) Late Grow Out

-   Fish older are then 3 months are transferred into 20 gallon tanks (if not already in a 20 gallon) and grown to 1 year of age in the Winter room.

## Stickleback Adults (1 year - 1.5 years) Breeding:

-   Adult fish are transferred to 20 gallon tanks in the long day room.
-   Fish can be kept at a density of 40 fish per tank if space is needed.
-   Adult fish become sexually mature 4-6 weeks after being in long day conditions and will stay in breeding condition for 1-3 months.

## Pipefish

-   Pregnant males are placed in 10.5 L tanks and moved back to 20 gallon tanks when the haev given birth.
-   Young pipefish (0-3 months) are grown in 10.5 L tanks at the density they are born at.
-   Adult pipefish are kept in mixed gender 20 gallon tanks at no more than 15 fish per tank.
