# Stickleback Embryo and Larval Euthanasia {#sec-husbandry_euthanasia_stickleback}

## Introduction

-   **Purpose**: This procedure describes best practices for euthanizing embryonic and larval threespine stickleback.
-   **Procedure Type**: Vertebrate Husbandry
-   **Species**:
    -   Threespine stickleback, (*Gasterosteus aculeatus*)
-   **Author**: Mark Currey\
-   **Date Created**: April 10, 2010, update January 1, 2014

## Materials

-   Container to hold fish while being euthanized.
-   Post mortem fixing equipment
-   Morgue (if needed)

## Solutions

-   Mesab Stock Solution {#sec-general_recipe_mesab}

-   Euthanasia strength Mesab (see below)

-   **Euthanasia Solution (300 mg/L)**:

    -   Make Mesab stock solution or obtain an aliquot from the freezer.
    -   Make a solution of 3.0 ppt Instant Ocean by adding 0.3 grams of Instant Ocean to 100 ml of DD water.
    -   Combine 7.5ml of stock solution into 100 ml of 3 ppt Instant Ocean.
    -   Store solution in an amber bottle to protect it from light and add mixed and expiration dates (6 months after being mixed) to the bottle.

## Procedure

**Procedure for embryo euthanasia**

```         
1.  Place embryos into a MS-222 euthanasia solution.
2.  Leave embryos in solution until movement has stopped, ~ 10 minutes.
3.  If fish is to be used for experiments, proceed with fixation or preparation for the experiment.
4.  If the fish are to be disposed of, place embryo in 95% ETOH for 5 minutes and then into morgue for disposal.
```

::: {.callout-warning title="NOTES"}
The last step is necessary as a startle response is not obvious in unhatched fish.
:::

**Procedure for larval euthanasia**

```         
1.   Place larva into a MS-222 euthanasia solution.
2.   Wait 10 minutes and perform a tap test to look for a startle response.
3.   If there is a response wait 5 minutes and repeat startle response test.
4.   Repeat this step every 5 minutes as needed.
5.   If there is no response move to fixing for post mortem experiments or place in morgue.
```

## Associated Papers

-   xxx
-   xxx
-   xxx
-   xxx
