# Stickleback Adult Anesthesia {#sec-sb_adult_anesthisia}

## Introduction

-   **Purpose**: This protocol descibes how to anesthitize adult threespine stickleback
-   **Procedure Type**: Anesthesia
-   **Species**:
    -   Threespine stickleback, (*Gasterosteus aculeatus*)
-   **Author**: Mark Currey\
-   **Date Created**: February 28th, 2024

## Materials

-   Petri dishes or fish container

## Solutions

-   MS-222 Stock solution of (4g/L, From Zebrafish Book 4th edition)

::: {.callout-warning title="NOTES"}
```         
Tricaine must be pharmaceutical-grade. We use tricaine purchased from Pentair, manufactured by Western Chemical and FDA approved. Tricaine (3-amino benzoic acid ethyl lester also called ethyl m-aminoboenzoate) comes in a powdered form. Purchase the smallest amount possible because tricaine expires quickly.
```
:::

**Mesab Stock Solution (4g/L) (tris buffered)**

```         
-   4 g tricaine powder
-   979 ml DD water
-   \~21 ml 1 M Tris (pH 9).
-   Adjust pH to \~7.
-   Aliquot in 50ml tubes, label with MESAB Stock Solution 4g/L, and store in a -20 freezer.
-   This makes 1 liter of solution.
```

**Anesthesia (168 mg/L)** - Make a solution of tris buffered Stock solution MS-222 solution as described above. (Or obtain a pre-made solution from freezer) - Make a solution of 3 ppt Instant Ocean by adding 0.3 grams of Instant Ocean to 100 ml of DD water. - Combine 7.5ml of stock solution into 100 ml of 3 ppt Instant Ocean. - Store solution in an amber bottle to protect it from light and add mixed and expiration dates (6 months after being mixed) to the bottle.

## Procedure:

```         
1.  Place fish into 168 mg/l MS-222 solution and wait for the fish to slow down.
2.  Image or do other experiments quickly to minimize fish exposure to MS-222. Pay attention to opercular movement to be sure that fish is alive.
3.  Revive by placing in fish water and moving fish gently through the water to pass water over gills.
```

## Associated Papers

-   xxx
-   xxx
-   xxx
-   xxx
