# cDNA basic {#sec-molecular-cDNA}

## Introduction

-   **Purpose**: This procedure describes how to synthesis cDNA for use with PCR.
-   **Procedure Type**: Molecular
-   **Species**: N/A

## Materials:

-   2 µl Oligo d(T)23 VN (50 µM, NEB; anchored-dT primer)\*
-   X µl up to 5 µg total RNA
-   1 µl 10 mM dNTP
-   water
-   2 µl 10x RT buffer (Invitrogen)
-   4 µl 25 mM MgCl2
-   2 µl 0.1 mM DTT -- Invitrogen
-   1 µl RNase inhibitor -- e.g., RNAseOUT (Invitrogen)
-   1 µl Superscript III reverse transcriptase (200 u/µl -- Invitrogen)

## Solutions:

NONE

## Procedure:

### First strand synthesis {#first-strand-synthesis .subhead}

Combine:

-   2 µl Oligo d(T)23 VN (50 µM, NEB; anchored-dT primer)\*
-   X µl up to 5 µg total RNA
-   1 µl 10 mM dNTP mix
-   Water (if necessary) to bring total to 10 µl

Heat to 65°C for 5 min., then ice

Collect contents at bottom of tube by brief centrifugation.

Add:

-   2 µl 10x RT buffer (Invitrogen)
-   4 µl 25 mM MgCl2
-   2 µl 0.1 mM DTT -- Invitrogen
-   1 µl RNase inhibitor -- e.g., RNAseOUT (Invitrogen)
-   1 µl Superscript III reverse transcriptase (200 u/µl -- Invitrogen)

Mix by gentle aspiration

-   25°C for 5 min.

### Reaction can be scaled up to accommodate more starting RNA

*Synthesis:* Incubate at 50°C for 50 min.

*Inactivation:* 85°C for 5 min. Chill on ice, collect contents to bottom by short spin.

*Destroy RNA template:* 1 µl RNase H (2 u/µl), incubate at 37°C for 20 min.

Proceed to PCR. Depending on expression level, may be able to use a dilution of cDNA as template -- try 1:50 dilution in EB, use 2 µl as template in a 20 µl reaction. Don't dilute your entire amount of cDNA, as some products may require a higher concentration of template.
