# Topo Cloning

## Introduction

-   **Purpose**: This procedure describes how to TOPO Clone with pCR4 Vector.
-   **Procedure Type**: xxx
-   **Species**: N/A
-   **Author**: xxx
-   **Date Created**: xxx

::: {.callout-warning title="NOTES"}
xxxx
:::

## Materials:

-   1 μl of salt solution
-   0.5 μl of vector
-   20 μl of TOP10 chemically competent cells
-   ice
-   400 μl of room temp SOC
-   bacterial plates
-   50 μl LB-Amp in round bottom plates
-   10.0 μl Lab PCR mix
-   0.25 μl T3/T7 Primer Pair
-   0.1 μl Taq
-   50 μl LB-Amp
-   14% Glycerol

## Procedure:

### TOPO Clone With pCR4 Vector

1.  Cut PCR bands from gels, freeze
2.  Vortex band tubes, then spin at 14000RPM for 10 min
3.  place at room temperature for 20 min
4.  add 20 μl of TOP10 chemically competent cells
5.  back on ice for 30 min
6.  heat shock at 42°C for 30 sec
7.  add 400 μl of room temp SOC, place at 37°C for one hour
8.  spread onto plates
9.  incubate overnight at 37°C

### PCR screen for Inserts

1.  Pick colonies from each plate with toothpick
2.  Into 50 μl LB-Amp in round bottom plates, 37°C for one hour
3.  Use 2 μl as template for PCR reaction, put plate back at 37°C

  ------ ------ ------------ -------- -----
  Step 1   \-     94°C   \-     5 min                 
  Step 2   \-     94°C   \-     45 sec   
  Step 3   \-     56°C   \-     45 sec   
  Step 4   \-     72°C   \-     1 min    37X for steps 2-4
  Step 5   \-     72°C   \-     5 min                 
  Step 6   \-     12°C   \-     indef            
  ------ ------ ------------ -------- -----

### Overnight: {#overnight .subhead}

-   Use 2 μl to inoculate 5 ml of LB-Amp, shake at 37°C overnight
-   Qiagen miniprep next day, ready to sequence

### Storage of Clones: {#storage-of-clones .subhead}

-   Grow clone plates overnight at 37°C
-   Next morning, add 50 μl LB-Amp, 14% Glycerol to each well (7% final)
-   Freeze for long term storage
